### PR TITLE
4143 Disable inappropriate xy options

### LINKED ISSUE #4143: Hide/Disable inappropriate XY Graphs
Currently when we open a file with single track, we show all the graphs available in the system. And when user chooses a graph that needs 2 tracks , we show empty graph. It would be good if we don't show those graph that needs 2 tracks if user opens a file with single track.
[Image from Gyazo](https://gyazo.com/afc05dcb26fa8cb1f1bc31e952caccaa)

### Steps:
1. Open boat1.rep
2. Open XY graph and select Range
3. See that it only contain Nelson track and yet Range , bearning and other graphs are enabled.
4. Select Range and see that no graph is shown, but all the graph toolbar buttons are enabled. Try to select each of them like this :

[Image from Gyazo](https://gyazo.com/2177345edd055cee4de06cf029f87aaf)

And selecting 'Copies the graph as a text matrix..' actions throws NPE :
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.Utilities.XYPlot.XYPlotUtilities.textMatrix(XYPlotUtilities.java:49)
	at MWC.Utilities.XYPlot.XYPlotUtilities.copyToClipboard(XYPlotUtilities.java:40)
	at org.mwc.debrief.lite.graph.GraphPanelToolbar$10.actionPerformed(GraphPanelToolbar.java:398)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)....

### LINKED ISSUE #4149: After resetting or closing files track names still reside in the XY graph's combo
After a user resets using NEW action or Closes a file, even if the graph resets/closes, still the tracks name are retained in the Select Tracks combo.
[Image from Gyazo](https://gyazo.com/f123a3967dedf4b180664bab82fa416f)

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4143 
Fix #4149

### CODE REVIEW

**Comment by IanMayo** [comment]
I'm playing with the branch. I've loaded `boat1.rep`

I only get offered "Bearing":
image

**Comment by saulhidalgoaular** [comment]
oh yes. It isn't finished. I did a backup/push of the code while we test the msi part. I will finish it soon.

**Comment by IanMayo** [comment]
sure, ok. No rush.

**Comment by IanMayo** [comment]
Thanks for spotting that @helenayele .  I think it's worth @saulhidalgoaular fixing it in this branch - it seems quite minor.

**Comment by saulhidalgoaular** [comment]
Good morning team. It has been fixed!!

**Comment by saulhidalgoaular** [comment]
Hi @helenayele . I have fixed what you mentioned, but I also see that the tote of all the tracks are still getting rendered despite they are removed. It is not directly related with this issue, but I am fixing it here anyways.

**Comment by helenayele** [comment]
Now the above issues are not reproducible, but after I delete all tracks from the outline view, I see that the graph combo still not empty. Can we fix this as well?.
[Image from Gyazo](https://gyazo.com/8934048453a240f8c572b37ad6c9da3c)

**Comment by IanMayo** [comment]
@saulhidalgoaular - could you implement Helen's last request please? Then we can get this issue closed :-)

**Comment by saulhidalgoaular** [comment]
Good morning.

I have implemented what Helen has mentioned. There is still to do the update of the tote information when a track is deleted. I have been debugging it and I see that it is keeping the old tracks in the list. Primary track and secondary track are also still outdated. I am filing it in a new issue so this one can be merged.

**Comment by helenayele** [comment]
Now after deleting the tracks from outline view, I can see that both the graph names list and tracks combo are empty. But the toolbar action items are still enabled and while clicking , they throw NPE - Exceptions.
So if we don't have any graphs shown on the pane, lets' disable all the actions.
[Image from Gyazo](https://gyazo.com/2ef7b02fffb0a8a9cef5339f9db6d9b8)
OR can we handle it at #4181

**Comment by IanMayo** [comment]
@saulhidalgoaular - let's handle it in the other issue.

**Comment by IanMayo** [comment]
@helenayele - have we either resolved the issues in this PR, or transferred them to other issues?


Can I merge it?

**Comment by helenayele** [comment]
Yes , please merge it, the last issue can be handled on  #4181.

**Pull request merged**
