### PR TITLE
added View action via org.eclipse.ui.menus

### PR DESCRIPTION
**Pull request by theanuradha**

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo  I create this for trial_release

**Comment by IanMayo** [comment]
@theanuradha - I see the build failed. I had a battle making Debrief build for my demo this morning.

I'll reproduce the steps in this branch tomorrow morning - it should work fine then.  I'll transfer this to myself.

**Comment by theanuradha** [comment]
@IanMayo  I will try to fix the build

**Comment by IanMayo** [comment]
Ok, if you wish.  One step I had to make was to change each Manifest.MF to specify JRE1.7, rather than 1.6 - which most had.  I think the major problem was with cmap.legacy, but I did it to all of them.

I also had to add the limpet plugins to the Debrief feature.

**Comment by theanuradha** [comment]
@IanMayo  Finnlay after lot of change build is valid now

**Pull request merged**
