### PR TITLE
5169 Eclipse ease compilation error fix

### LINKED ISSUE #5169: Problem building from source - not able to find org.eclipse.ease.feature.feature.group
### Discussed in https://github.com/debrief/debrief/discussions/5168

<div type='discussions-op-text'>

<sup>Originally posted by **bradh** January 19, 2023</sup>
I'm trying to build from source (using command line maven), but hitting this:

```
[INFO] Scanning for projects...
[INFO] Resolving target definition file:/home/bradh/coding/debrief/org.mwc.debrief.targetplatforms/eclipse-latest.target for environments=[linux/gtk/x86_64, win32/win32/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-11' { source level: 11, target level: 11}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@5cd71ee2...
[ERROR] Failed to resolve target definition file:/home/bradh/coding/debrief/org.mwc.debrief.targetplatforms/eclipse-latest.target: Could not find "org.eclipse.ease.feature.feature.group/0.8.0.I202105061131" in the repositories of the current location -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

Any ideas for a source for that?</div>

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #5169 

Good morning.

I have fixed this specific problem, however there are other fixes / improvements I would suggest to do.

* Update to Eclipse Ease 0.9
* Fixing some Java calls to deprecated, which will give compilation errors in the latest Java 11 version.
* Merging Eclipse Easy Python integration into Develop.

### CODE REVIEW

**Comment by bradh** [comment]
I checked this with a local build (manually applying the change), and it resolves my issue.

**Comment by IanMayo** [comment]
> Merging Eclipse Easy Python integration into Develop.

Noted. I've added a comment about moving the installation/usage guidance to the relevant part of the tutorial.  Once we've got that done, I'll merge it, and we can get the other fixes done.

**Review by IanMayo — APPROVED** [review]

**Review by IanMayo — CHANGES_REQUESTED** [review]
Oops, it looks like there are some package changes that are breaking the build.
image

**Comment by bradh** [comment]
> Oops, it looks like there are some package changes that are breaking the build. image

I think those are fixed by #5172, which probably should go in first.

**Comment by saulhidalgoaular** [comment]
I am closing this PR because It was covered in https://github.com/debrief/debrief/pull/5174

**Pull request closed without merging**
