### PR TITLE
issue #728 - Expanding the XY Plot View, Plot disappears (MS WINDOWS)

### PR DESCRIPTION
**Pull request by pecko**
NOT READY TO MERGE

I have played with some recommended SWT_AWT options. See http://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet154.java

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks - may get chance to check in MS Windows tomorrow afternoon, else Monday.

**Comment by pecko** [comment]
Please try to play with

```
java.awt.Toolkit.getDefaultToolkit().setDynamicLayout(false);
```

It is commented in the PR, but you can try with true and false.

**Comment by IanMayo** [comment]
@pecko  the ````setDynamicLayout()```` option doesn't have any effect.  But the new Swing construct strategy fixes it perfectly.  

Could you include a code comment that explains why/how the new strategy works?

**Comment by pecko** [comment]
I have used the code from this snippet: http://git.eclipse.org/c/platform/eclipse.platform.swt.git/plain/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet154.java

Main change is adding a Swing component to panel with overridden update method.

**Comment by IanMayo** [comment]
I'll put in a good comment, then merge.

**Comment by pecko** [comment]
I have rebased and merge this PR. @IanMayo You can apply when you think that it's ready.

**Comment by IanMayo** [comment]
The fix works perfectly, thanks.

**Pull request merged**
