### PR TITLE
fix combo repain issues on dlite

### PR DESCRIPTION
**Pull request by theanuradha**

### CODE REVIEW

**Comment by theanuradha** [comment]
#3886

**Comment by IanMayo** [comment]
@theanuradha - we've got some static analysis warnings for the new code (see Codacy review above).

I just tried to fix them, but couldn't checkout the branch. When I did, I couldn't push back to your repo.

Would you mind going in to fix the compiler warnings for the above code please?

**Comment by theanuradha** [comment]
@IanMayo should be fine now

**Comment by IanMayo** [comment]
@theanuradha - I think this PR introduced a bug for the combo:

> there is also issue in layers combo selection - it always default to User Selected layer 
> option - even if I select like the other options , when I try to insert shapes  - 
> it comes back the user selected layer option - https://gyazo.com/4e06ab68d7dbee6a6c4390d0314465e2
> See in the video, after I select Chart features when I try to insert shape, the combo 
> selects the user Selected layer by itself

**Pull request merged**
