### PR TITLE
4866 Refactoring/Code Cleaning Up and Removal of Unneeded variables.

### LINKED ISSUE #4866: Remove Unused Variables from the Time Window Algorithm and Creating Unit Tests
Remove Unused Variables from the Time Window Algorithm and Creating Unit Tests

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4866

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
[excel.zip](https://github.com/debrief/debrief/files/4640183/excel.zip)

**Comment by IanMayo** [comment]
@helenayele  - could you please check that those weird new course/speed graphs show properly?

**Comment by IanMayo** [comment]
Runtime bug captured by @saulhidalgoaular  as #4880

**Comment by IanMayo** [comment]
@helenayele  - would you mind approving, now that the bug has been moved to another issue?
https://github.com/debrief/debrief/pull/4867#issuecomment-633498221

**Comment by helenayele** [comment]
sure

**Pull request merged**
