### PR TITLE
make sure to centre to current display

### PR DESCRIPTION
**Pull request by theanuradha**
image

### CODE REVIEW

**Comment by IanMayo** [comment]
Hmm, on Linux (Mint Cinnamon) I'm not getting the title bar:
image


In your screenshot, you have the title bar, but now the contents of the **setMessage** call in **ImportRepFreqDialog.create()** method.

Could you flash up your Linux VM & Investigate this?

**Comment by theanuradha** [comment]
@IanMayo  I will

**Comment by IanMayo** [comment]
@theanuradha - any luck with that fix?

I'd like to include it in a new build.

**Comment by theanuradha** [comment]
@IanMayo  added fix now testing on mac

**Comment by IanMayo** [comment]
@theanuradha - working on Linux, that's enough for me to merge it.

But, there is the remaining issue that the *setMessage* content isn't displayed, as described [above](https://github.com/debrief/debrief/pull/2004#issuecomment-257609786)

**Comment by theanuradha** [comment]
ok I will check Set message

**Comment by IanMayo** [comment]
Getting NPE:
````
!ENTRY org.mwc.debrief.core 4 0 2016-11-02 14:31:32.535
!MESSAGE Problem loading datafile:/home/ian/git/debrief/org.mwc.cmap.combined.feature/root_installs/sample_data/boat1.rep
!STACK 0
java.lang.NullPointerException
	at org.mwc.cmap.core.ui_support.SelectImportModeDialog.open(SelectImportModeDialog.java:138)
	at org.mwc.cmap.core.DebriefToolParent$1.run(DebriefToolParent.java:178)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
````

I get this when re-opening Debrief.  Steps to reproduce:

1. Open Debrief
2. Load **boat1.rep**
3. Close Debrief
4. Re-open Debrief

Debrief will try to re-open the import freq dialog.  But, there isn't an active shell, yet.  So, we get an NPE at SelectImportModeDialog.java#138

**Comment by IanMayo** [comment]
Oh, I also get the same NPE when I drag/drop boat1.rep from the Linux file manager.  I don't get it when dragging from the Navigator view, but I do from outside Debrief

**Comment by theanuradha** [comment]
@IanMayo  NPE is fixed ! under linux ImportRepFreqDialog not getting Window trim im trying to fix that

**Comment by theanuradha** [comment]
@IanMayo I'm little loss over why ImportRepFreqDialog not getting it Window trim

**Comment by theanuradha** [comment]
image

Ok seems fixed now Please review

**Pull request merged**
