### PR TITLE
Issue #1089 - XY Plots don't show in OSX

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
Just tried in OSX.  The XYPlot View pane now opens, but it's empty.

**Comment by pecko** [comment]
Could you try some SWT snippet, for instance, http://git.eclipse.org/c/platform/eclipse.platform.swt.git/plain/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet154.java

**Comment by IanMayo** [comment]
Have conducted SWT Snippets Trial.

In Eclipse LUNA we don't need to include the "special" java lines to run the demo.

Under 3.8.2, the window was blank when it opened, but when I resized it the table of items appeared - though it wouldn't fill the window area - there was a permanent border.

The last thing I can think of is to trial switching to using charts based on the jfreechart-swt.jar component.

Could you try that?

**Comment by IanMayo** [comment]
This PR didn't fix the OSX Charting issue - so we'll have to ditch it.

**Pull request closed without merging**
