### PR TITLE
3762 popup editor

### LINKED ISSUE #3762: Properties window is not available for some layers in D-Lite
In D-Lite, we don't show any properties for some layers see the screenshots below
[Image from Gyazo](https://gyazo.com/12ba5a386f6fc284493c884dfc74f689)

### Steps to Reproduce
1. Open BULK_BLUE_TRACKS.rep on D-Lite
2. Expand Track:HVU  and double click 121213.14(97 positions) layer to open its property window
See that nothing is shown.
But in full debrief , its property is shown like this:
image

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #3762

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - could you check to see if i've missed out any Outline types that don't provide a popup editor?

**Comment by IanMayo** [comment]
@helenayele - hopefully fixed

**Comment by helenayele** [comment]
And also I tried to check by opening most of the rep and dpf file from sample_data and  I get all items's property window opened.

**Comment by helenayele** [comment]
Yes , now able to approve my changes without any issue. But after approving my changes when I select reset it logs exception but this is filed as separate issue on #4150

**Pull request merged**
