### PR TITLE
4461 crash on snail mode

### LINKED ISSUE #4461: Issues while opening compositeTrack file
When I open 'compositeTrack.dpf' file from old Debrief version's sample_data folder, I get the below error dialog:
[Image from Gyazo](https://gyazo.com/3a7c6cc854ff49889388f9c076716b32)
The file is this 
[compositeTrack.zip](https://github.com/debrief/debrief/files/3495678/compositeTrack.zip)

And this is logged 
 java.lang.ClassCastException: Debrief.GUI.Tote.Painters.SnailPainter2 cannot be cast to Debrief.GUI.Tote.Painters.SnailPainter
	at Debrief.ReaderWriter.XML.GUI.StepperHandler.makeThis(StepperHandler.java:64)
	at Debrief.ReaderWriter.XML.GUIHandler.addThisComponent(GUIHandler.java:97)
	at Debrief.ReaderWriter.XML.GUIHandler$1.addComponent(GUIHandler.java:66)
	at Debrief.ReaderWriter.XML.GUI.ComponentHandler.elementClosed(ComponentHandler.java:59)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReader.endElement(MWCXMLReader.java:259)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.doImport(MWCXMLReaderWriter.java:170)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.importThis(MWCXMLReaderWriter.java:333)
	at Debrief.ReaderWriter.XML.DebriefXMLReaderWriter.importThis(DebriefXMLReaderWriter.java:121)
	at org.mwc.debrief.lite.DebriefLiteApp.handleImportDPF(DebriefLiteApp.java:1240)
	at org.mwc.debrief.lite.DebriefLiteApp.FilesReceived(DebriefLiteApp.java:1198)
	at MWC.GUI.DragDrop.FileDropSupport.fileReceived(FileDropSupport.java:145)
	at MWC.GUI.DragDrop.FileDropSupport.drop(FileDropSupport.java:179)
	at java.awt.dnd.DropTarget.drop(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4461 
It doesn't crash now. What I see is that in Full Debrief it automatically changes to Snail Perspective. Do we implement it in Debrief Lite?
and, I also see it changes to snail perspective only if there is no opened file (In Full Debrief). If there is a file opened. It keeps the previous perspective.

### CODE REVIEW

**Comment by helenayele** [comment]
The above comment is given by mistake

**Comment by IanMayo** [comment]
@helenayele - does D-Lite switch to the correct normal/snail mode according to how the plot was saved?

**Comment by helenayele** [comment]
No No it didn't switch, I approved this by mistake, sorry.

**Comment by IanMayo** [comment]
Ok.  When we save a plot, the Normal/Snail mode gets stored in the `.dpf` file.  It's near the end of the file.  When we re-load a plot, Debrief _should_ switch to the correct normal/snail mode.

We aren't able to do it currently in D-Lite, since we can't change the toggle on the toolbar. So, we change the plot to match what's currently on the toolbar.

Once @saulhidalgoaular has updated Flamingo (ribbon bar), we can change the toggle, and correctly implement setting the mode according to how it was saved.

Hmm. I'm pretty sure that feature is covered in a different Issue.  If so, we can close this one - since it works otherwise.

**Pull request merged**
