### PR TITLE
Added FilteredGrid Component

### PR DESCRIPTION
**Pull request by theanuradha**
image

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo  highlighting yet but will add next

**Comment by IanMayo** [comment]
Hey, it works really well, even with 12000 narrative entries.

**Comment by IanMayo** [comment]
Have made minor change to remove the object that is just for the Grid control, and to extend the text guidance that is shown for an empty search box.

As ever, please Pull before you carry on with development.

**Comment by IanMayo** [comment]
@theanuradha - ok if I merge this version?  I'd like to use it in a build, and start getting some feedback.

**Pull request merged**
