### PR TITLE
#2147 update icons to new spec

### PR DESCRIPTION
**Pull request by theanuradha**
ref:https://github.com/debrief/debrief/issues/2147

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo missing icons logged at https://github.com/debrief/debrief-icons/issues/44

**Comment by theanuradha** [comment]
image

**Comment by theanuradha** [comment]
image

**Comment by IanMayo** [comment]
@theanuradha - I see we're missing icons for the "down" state for the **View** toolbar.  Is there a Swing UI capability to draw the existing icon in a "down" state?  This will avoid having to create new ones.

**Comment by theanuradha** [comment]
@IanMayo **"hand"** you referring ? or zoom

**Comment by IanMayo** [comment]
@theanuradha oops, the Zoom-In button.  New Debrief has a "Pan" icon, it's the blue hand, called **hand.png** in the debrief-icons repo.

@theanuradha - There's a VPF icon in new Debrief (**vpf.png**). The app is showing "VPF Layers" - as if the icon can't be found.

**Comment by IanMayo** [comment]
@theanuradha - could we also move to the new Debrief VCR Time-Controls?  The Play Button has its own Pause version.  So, I guess you'll have to rename pause.png to play_.png (or something like that).

**Comment by theanuradha** [comment]
vpf icon is fixed

**Comment by theanuradha** [comment]
@IanMayo we already have zoomin.png not sure why it not load in app

**Comment by theanuradha** [comment]
image

**Comment by theanuradha** [comment]
@IanMayo ok zoominpng works just we need those _.gif images missing issue sorted those are 32x32 in old spec

**Comment by theanuradha** [comment]
image

**Comment by IanMayo** [comment]
So, for zoomin, we have "up" state in png, but the "down" state is in gif.  As I said earlier, is there a Swing capability to apply styling to an "up" toggle button icon  to make it look like a "down" toggle button?.

**Comment by IanMayo** [comment]
You mentioned that the old icons are 32px. We only have 16px or 24px.  Would you mind switching to the 24px icons? They'll be closer to the existing ones.

**Comment by theanuradha** [comment]
@IanMayo Sure I will try to render toggle state

**Comment by IanMayo** [comment]
Ok, @theanuradha - while I'm giving you lots of jobs...  For the icons on the **Drawing** toolbar, could you use the icons with the Red "add" icon at the bottom-right?  (they are named as **rectangle_add.png**)

**Comment by theanuradha** [comment]
image

**Comment by IanMayo** [comment]
Yes, that selected mode is fine :-)

**Comment by theanuradha** [comment]
Add icons added 
image

**Comment by theanuradha** [comment]
@IanMayo pan icon also updated

**Pull request merged**
