### PR TITLE
4434 Use relevant constant for how many segments to use

### LINKED ISSUE #4434: Circles rendered as polygons
Circle Shapes are being plotted with too few coordinates:
image

An optimisation that was introduced as part of the performance review in early July was mistakenly left in the production code.

A final constant indicates how many elements there should be:
````
	/**
	 * the number of segments to use to plot this shape (when applicable)
	 */
	public static final int NUM_SEGMENTS = 40;

````

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #4434

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - could you check this works for you? 

Could you also check that you don't get a performance issue when viewing large tracks in snail mode?

(in snail mode, the default ship marker is a circle - I _think_ I was trying to optimise snail mode when I introduced the problem)

**Comment by IanMayo** [comment]
@helenayele - could you send me a copy of your `sample_lots_of_sensors.dpf` file?  You've got a different version to me, and I'd like to test using your copy.

**Comment by helenayele** [comment]
Please find here
[sample_lots_of_sensors.zip](https://github.com/debrief/debrief/files/3475496/sample_lots_of_sensors.zip)

**Comment by IanMayo** [comment]
@helenayele - but you can verify the circle plotting issue is fixed, right?

**Comment by IanMayo** [comment]
Merging - since I want to get a release out.

**Comment by helenayele** [comment]
Sure, sorry didn't see it on time, yes circle is plotted without any issues like this :
[Image from Gyazo](https://gyazo.com/dbfef25a4d7d64a008cc4fc9f96caef0)

**Pull request merged**
