### PR TITLE
Issue 1721 save icons update

### PR DESCRIPTION
**Pull request by theanuradha**
save-menu-fix

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo  if u prefer to have separate icons for save,saveAll,saveAs please add new icons so we can update.

**Comment by IanMayo** [comment]
Yes, let's wait for the updated icons.

**Comment by IanMayo** [comment]
@theanuradha  - I've added the new icons to this branch. Could you finish it off?

**Comment by theanuradha** [comment]
save-menu-fix-2

**Pull request merged**
