### PR TITLE
4874 better diagnostic

### LINKED ISSUE #4874: Pepys Database connection - better diagnostics
I'm playing with connecting to different Pepys databases (SQLite and Postgres).

It would be useful if the dialog shown after "Connection test" showed the value of `PEPYS_CONFIG_FILE` variable. This would make me absolutely sure which config file was being used.

The file path/name would be visible whether the connection was successful for unsuccessful.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4874

### CODE REVIEW

**Comment by IanMayo** [comment]
@saulhidalgoaular - there's a minor conflict to resolve.  But, when you're resolving the conflict, could you include method javadoc comments please?

**Comment by saulhidalgoaular** [comment]
> @saulhidalgoaular - there's a minor conflict to resolve. But, when you're resolving the conflict, could you include method javadoc comments please?

Hello @IanMayo I have solved the conflict and added documentation. In case you consider It is convenient to add more documentation, please, don't hesitate to tell me.

**Comment by IanMayo** [comment]
nice work @saulhidalgoaular

**Comment by helenayele** [comment]
Still reproducible...

**Comment by helenayele** [comment]
When I use incorrect config file like debrief\org.mwc.cmap.combined.feature\root_installs\sample_data\other_formats\ pepys.sqlite , 
I got [Image from Gyazo](https://gyazo.com/e07658e8e52601f29bd609a52df3d228) error message. 
But when I use unavailable file in the system,
like 
[Image from Gyazo](https://gyazo.com/372dad9fe950548a2cbc24a6443368ea)

 it doesn't show the 'Pepys Import" dialog at all and it shows me this dialog :
[Image from Gyazo](https://gyazo.com/b0dfcacaf3fc9013f211b9b789582c32)

Is this by design?

**Pull request merged**
