### PR TITLE
Issue #1161 - English language property names

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
@pecko - I've got a new user that I'd like to send a CD to, including this new update.  Can you give me an estimate on when you'll get chance to do the automatic testing?

**Comment by IanMayo** [comment]
@pecko  - I'm keen to have a greater understanding of the test strategy here.  Why to they need to be JUnit Plugin tests?  They don't seem to need UI - so can't they just be JUnit tests?

**Comment by IanMayo** [comment]
@pecko - a second query.  I've just made a breaking change (extra "L" on the end of "Label", to check that the tests work:

fixlabel

But, no test errors were reported:
editabletests

The tests were run from Maven. But, it looks like they aren't doing the job we require of them.

**Comment by pecko** [comment]
> @pecko - I'm keen to have a greater understanding of the test strategy here. Why to they need to be 
> JUnit Plugin tests? They don't seem to need UI - so can't they just be JUnit tests?

We use JUnit Plugin tests because we have to create a environment to find hierarchy and to instantiate Editable classes (projects, classpath ...). It probably can be done in another way, but this is the simplest.
Tests don' run in UI mode, but SWTCanvasAdapter have to be created in UI mode and this test is handled specially.

**Comment by pecko** [comment]
> a second query. I've just made a breaking change (extra "L" on the end of "Label", to check that the 
> tests work:

I have tested it in PDE (IDE), but not in maven build. Maybe I have changed something later. Namely, just calling getPropertyDescriptors will throw an exception if there is invalid property name.

Will check ...

**Comment by pecko** [comment]
> I've just made a breaking change (extra "L" on the end of "Label", to check that the tests work:

You have changed getGriddablePropertyDescriptors, but not getPropertyDescriptors
The test checked only getPropertyDescriptors. I have added checking for getGriddablePropertyDescriptors 9will commit it shortly)

BTW: 
- we can just discover the class where some property name (or names) are wrong. We can't discover exactly property because Debrief catch the IntrospectionException and hide it (return null mostly).
- there are cca 240 classes which are tested

**Comment by pecko** [comment]
I have updated the PR.

@IanMayo you can repeat your test with the label property.

**Comment by IanMayo** [comment]
Great - working fine.

**Pull request merged**
