### PR TITLE
specifically refreshed the changed layer in case of narratives

### LINKED ISSUE #4134: Refresh issues with large Narrative files
For very large narrative entries (> 1000) , after editing any of the entries and applying, D-Lite will take so much time to refresh and show the new updated value.

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #4134

### CODE REVIEW

**Comment by IanMayo** [comment]
@ayeshare - I've done a bit of refactoring, so please pull my changes before you start work on @helenayele 's issue(s).

**Comment by helenayele** [comment]
@IanMayo with your change now,  I am not able to reproduce the above issue 
[Image from Gyazo](https://gyazo.com/06688302063d3d97c79f5611b76b11fb)

**Comment by IanMayo** [comment]
I fixed it? Well, I wasn't expecting that :-) . Let's wait for @ayeshare to verify I haven't broken her code.

**Comment by helenayele** [comment]
sure @IanMayo

**Comment by ayeshare** [comment]
@IanMayo It works fine. No regressions

**Comment by IanMayo** [comment]
@helenayele - I'm going to merge it, since I don't expect the sea-riders to produce narratives with 1000s of entries.

**Comment by helenayele** [comment]
okay

**Comment by ayeshare** [comment]
> Thanks Ayesha, it is now very fast.
> But I see unnecessary undo and redo actions, clicking on undo/redo doesn't have any action seen for the user. is there any background work.
> 
> See the video, even if I click undo/redo 2 -3 times, I see nothing changed.

Yes, I am seeing this problem when some shapes are already present.  The problem is that the entire tree is refreshed after deleting a shape.

**Comment by helenayele** [comment]
> Yes, I am seeing this problem when some shapes are already present. The problem is that the entire tree > is refreshed after deleting a shape.
But I see this even I don't delete anything the above step can be taken as example, I just change the time, and apply.

**Comment by IanMayo** [comment]
@ayeshare: we introduced an optimisation for when a narrative is entered - when a narrative entry is modified, only update the narratives layer.

But, @helenayele has highlighted the problem that we have a performance problem when a non-narrative entry is modified.  _Maybe_ we need to look at the profiler and see what is causing the performance problem.  _Maybe_ there's another modification we can make - such as only modifying a tree node if it has changed.

**Pull request merged**
