### PR TITLE
Fixed a copy paste bug, by cloning objects before pasting

### LINKED ISSUE #4937: Outline view does't show shapes after copy and paste actions
If we copy a shape and paste it in another folder, the outline view doesn't show it but it is being shown in map panel. 
But it shows the item in outline view if we cut and paste it.

And also we can't paste a shape after we copy it more than once. But we should be allowed to paste it as many times as possible once we copy it.

Here is the video:
[Image from Gyazo](https://gyazo.com/22fc3af369366b9f61f50b33819d0ca4)

Cut /paste action:
[Image from Gyazo](https://gyazo.com/0d1f0226b90aeedc7853a8ea2181c19b)

Copy and paste many times:
[Image from Gyazo](https://gyazo.com/47ba803901647add4a3c927a2ce8aa8d)

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #4937

### CODE REVIEW

**Review by helenayele — APPROVED** [review]
Now undo/redo actions work as expected.

And the cut/paste or copy/paste actions work well also.
So approving...

**Comment by IanMayo** [comment]
@ayeshare  - are you happy that this is completed?

**Comment by ayeshare** [comment]
> @ayeshare - are you happy that this is completed?

yes I am 👍

**Comment by ayeshare** [comment]
@IanMayo I am waiting for this to be merged to test if #4129 will also get fixed

**Comment by ayeshare** [comment]
@IanMayo the bug is now fixed.

**Pull request merged**
