### PR TITLE
3697 error handling while loading files

### LINKED ISSUE #3697: When dragging and dropping non-rep file on the D-Lite, it silently fails
When dragging and dropping non-rep file on the D-Lite, it fails silently, no proper warning dialog is shown . Sometimes it  shows this error dialog 
[Image from Gyazo](https://gyazo.com/9fec1152e326d662d88cb500787f0f47) and logs  this 
[DynamicLayer handler not found.txt](https://github.com/debrief/debrief/files/2832784/DynamicLayer.handler.not.found.txt)

### Expected Result
It should show warning Message ,that informs the user that he/she should drag-drop only rep files.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #3697

### CODE REVIEW

**Comment by IanMayo** [comment]
@saulhidalgoaular - it looks like Helen has some outstanding comments on this. Would you mind checking them?

**Comment by IanMayo** [comment]
I'm still working on that dialog, in this PR #4007

**Comment by helenayele** [comment]
Okay  ,thanks

**Comment by IanMayo** [comment]
@helenayele - I've merged my `dynamic layers` fixes into this PR.  Hopefully you can approve it.

**Comment by IanMayo** [comment]
@helenayele - that's not a Debrief file

Is this a more acceptable error message:
image

**Comment by helenayele** [comment]
Yes, it is acceptable to me. I tried all problematic dpf files, and they are opened well. May be some of them throws stackoverflow exception when I opened the time  play  and will track this in separate issues. So anything you want me to check on this pr?

**Comment by IanMayo** [comment]
@helenayele - no, nothing more to check, thanks.

**Comment by IanMayo** [comment]
Yes, please track it in a separate issue.

Could you assign it to @saulhidalgoaular - he's the expert on the time controls.

**Pull request merged**
