### PR TITLE
202103_build

### PR DESCRIPTION
**Pull request by theanuradha**
prototype build

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @theanuradha 

I opened Eclipse, opened `eclipse-latest.target`, clicked on `Reload target platform`.

When I ran Debrief I got these dependency errors:
image

Then this:
image

I've attached the error log.
[debrief_lot.txt](https://github.com/debrief/debrief/files/6363973/debrief_lot.txt)

**Comment by IanMayo** [comment]
Thanks @theanuradha  - you gave me feedback via UpWork.  I downloaded & installed 2021-03.  After doing `target install` I just have this one unresolved dependency:
image

If I ignore the warning the application opens correctly (though possibly without EASE support).

**Comment by theanuradha** [comment]
> Thanks @theanuradha - you gave me feedback via UpWork. I downloaded & installed 2021-03. After doing `target install` I just have this one unresolved dependency:
> image
> 
> If I ignore the warning the application opens correctly (though possibly without EASE support).
> 
> Note: the `mvn clean verify` still fails with the `org.freehep` dependency error.

you on my branch ? as it seems build correct on build server as well 

can you give error you get on build ?

**Comment by theanuradha** [comment]
> > Thanks @theanuradha - you gave me feedback via UpWork. I downloaded & installed 2021-03. After doing `target install` I just have this one unresolved dependency:
> > image
> > If I ignore the warning the application opens correctly (though possibly without EASE support).
> > Note: the `mvn clean verify` still fails with the `org.freehep` dependency error.
> 
> you on my branch ? as it seems build correct on build server as well
> 
> can you give error you get on build ?

Also can you reload target file and do clean build ?

**Comment by IanMayo** [comment]
This screenshot shows the branch we're in, and the version of object web required:
image

Here is the version in the target:
image

Here is the version specified in the Product run configuration:
image

When I change the objectweb version in the runtime configuration to 5.0 Debrief opens without the warning:
image

**Comment by IanMayo** [comment]
Closing. Actual solution was in another PR #5065

**Pull request closed without merging**
