### PR TITLE
4099 narratives

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Supports #4099

Please, don't merge yet. Listeners still missing.

### CODE REVIEW

**Comment by IanMayo** [comment]
Yes, @saulhidalgoaular - could you attempt a layout that's closer to Celine's?

image

The important parts of the layout seem to be:
* line of metadata (time, source, type)
* line of content, with optional word-wrap.

**Comment by IanMayo** [comment]
@helenayele - this is just the first phase:
https://docs.google.com/drawings/d/1-rM1Mjhf1rq8ouLfGMaTJTZpIMZ4cPplO_aqLy38Xxc/edit

I believe that the only button that needs to be implemented for phase 1 is the `Word wrap` toggle.

**Comment by helenayele** [comment]
Narratives are shown for dpf files as well
Able to reset narratives entries after file is closed
#### Issues 
1. Some narratives are listed outside of narrative border see this :
[Image from Gyazo](https://gyazo.com/54e504cd1077b99cee4363958cd8c6ea)

2.  Texts on second line of narrative entry are not fully shown - [Image from Gyazo](https://gyazo.com/4ef171c79128f22a88790fe949b842fd)

**Comment by helenayele** [comment]
We need Refresh action after enabling/disabling Wrap Text functionality. Currently after enabling 'Wrap to Text' its effect is only seen when we select the narrative entry.
[Image from Gyazo](https://gyazo.com/40e106d24a2aa56f36cb49d57721c7a3)

**Comment by helenayele** [comment]
2 more issues:
 1 -  We need to show all texts in narrative entries. Currently we show only 2 lines of text when 'Word Wrap' is enabled.
[Image from Gyazo](https://gyazo.com/cf09c851f43edebbbab6f85953331b6a)
2 - 'Word Wrap' button needs tool-tip

**Comment by IanMayo** [comment]
More feedback.

## 1. Too much vertical separation

There is too much whitespace between the rows, it means fewer roles than possible are displayed

image

## 2. Doesn't expand to fill horizontal space

Because the rows don't consume horizontal space, we're again prevented from seeing the maximum possible rows.

image

It we allowed the panel to fill the horizontal space, it would make a long line like this legible:
image

**Comment by helenayele** [comment]
Currently , narrative entry gets expanded when we increase width  and the remaing items are :

1- Height of the narrative entry should be dynamic - now it seems all entries have got the same height
2.  The upper parts like DTG, Type/source are not fully shown
See the below video
[Image from Gyazo](https://gyazo.com/c070223b30512b1cc185bba40dda6e41)

**Comment by helenayele** [comment]
Now it looks like :
[Image from Gyazo](https://gyazo.com/5eef7f2befa3cc058918bc6b69c2e894)
 - When we increase the width of the narrative panel, the entry width also increase
- The entry height has got fixed size
- The upper parts like DTG, Type/source are not fully shown

**Pull request merged**
