### PR TITLE
4525 range bearing

### LINKED ISSUE #4525: [11] Funny behavior if you right click while measuring range and bearing
While measuring range and bearing, if you right click at the end of the measured line, the line doesn't get removed when you release the mouse.

### Steps to reproduce

1. Open boat1.rep or any file with track information
2. Open View menu > Select Rng/Brg button
3. Put your cursor on one end of the track and drag to a position ,when you reach at the end of your position , right click
4. Then click on other positions
5. See that the line stays there.
[Image from Gyazo](https://gyazo.com/39b1c8d93a7a41a297ad68af57e3bd28)
### Expected result
The line should be removed when mouse is released even if user right clicks or not.
In full debrief, when user right clicks it shows this context menus :
[Image from Gyazo](https://gyazo.com/a13979ff0e0e7eaad4f9fbe78550c50a)

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4525

### CODE REVIEW

**Comment by IanMayo** [comment]
One outstanding issue, please @saulhidalgoaular 

If I start dragging with left button, but then click the right button, the Range/Brg status bar gets stuck on zero range and bearing:
https://youtu.be/hrGivsVwXb0

image

I think you need to introduce your `buttonPressed` member field into `RangeBearingTool`

**Comment by IanMayo** [comment]
@helenayele - didn't you encounter the bug I reported earlier?
https://github.com/debrief/debrief/pull/4556#issuecomment-537433179

**Comment by helenayele** [comment]
No , I didn't encounter the rng 0 brg 0 reading when I right-click before.

**Comment by IanMayo** [comment]
Ok, I'm still getting it.  If I right click during a range-bearing measurement, the displayed range bearing sticks at zero.

Hey, look at my fancy animated gif!

[Image from Gyazo](https://gyazo.com/87ee092225b706baf37a574e40632ef2)

**Comment by saulhidalgoaular** [comment]
> Ok, I'm still getting it. If I right click during a range-bearing measurement, the displayed range bearing sticks at zero.
> 
> Hey, look at my fancy animated gif!
> 
> [Image from Gyazo](https://gyazo.com/87ee092225b706baf37a574e40632ef2)

oh @IanMayo . Well spotted. It is fixed now.

**Comment by helenayele** [comment]
Hmm, Okay , I was able to reproduce it before the fix. But now I can't reproduce, when I right-click , it stays on the correct reading of rng/brg 
[Image from Gyazo](https://gyazo.com/b2a13ce4f3876e133c15020386c8963b)

**Pull request merged**
