### PR TITLE
 Put new Debrief icon into Windows launcher #1137

### PR DESCRIPTION
**Pull request by kumarbabu**

### CODE REVIEW

**Comment by IanMayo** [comment]
Quick feedback: the smaller icons are really pixelated.  We have icons specifically drawn at the smaller resolutions - we should use them.

**Comment by IanMayo** [comment]
Ahh, maybe OSX Preview isn't the best viewer.  If the small icons are crisp for you, I'm sure they will be crisp for me.  But, if they aren't crisp for you, then you need to replace them with better ones.

**Comment by kumarbabu** [comment]
Hi, in windows photo viewer, those icons are looking well. One more thing I would like to share. we are manipulating the pixels and bits for those generated 7 icons, the way did for old debrief launcher icon. see below,

debrief ico2

**Comment by IanMayo** [comment]
Check in MS Windows - working fine :-)

**Pull request merged**
