### PR TITLE
4079 graph disposal for invalid selection

### LINKED ISSUE #4079: Graph is not disposed while  un-selecting the last track
See the issue in this video:
[Image from Gyazo](https://gyazo.com/6404fcb290084d5c128a323c8c33ab14)

### Steps to reproduce:

1. Open sample.dpf
2. Select Course graph 
3. Select both Nelson and COLLINGWOOD tracks
4. Now un-select COLLINGWOOD   - see that the graph for this track is disposed
5, Then unselect again Nelson
See that Nelson graph is not displosed/hidden

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4079

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Hi team.

I have branched 4053 because I needed the reset method that I've created there.

**Comment by saulhidalgoaular** [comment]
I am seeing now that this patch introduces a new behavior that we need to confirm if it is wanted.

There are many operations that reset the track list, which unselect the tracks in the XY panel and now will also trigger this method that cleans the graph. For example, when I rename a track, track list is reassigned, but the previous XY plot might still be valid.

An approach to it might be to have a default method to display (which means a default selection). It could be maybe the "last operation". What is your opinion about it @IanMayo and @helenayele ?

Check out the branch and play with it to understand what I mean.

**Comment by IanMayo** [comment]
@saulhidalgoaular - I must be doing something wrong. I can't get two tracks in the track listing.

Here is what I tried:
* open Debrief Lite
* select `boat1.rep` and `boat2.rep` in file manager.  
* drag/drop files into Debrief
* `Select tracks` menu is empty

Then I tried:
* open D-Lite
* drag in `boat1t.dpf`
* `Nelson` available in `Select tracks`
* View graph of `Course` - great
* drag in `boat2.rep`
* `Select tracks` still only contains `Nelson`

Hmm, @helenayele - is this what you get, too?

**Comment by saulhidalgoaular** [comment]
Good afternoon @IanMayo . I see you have spotted a new bug. I am fixing it.

**Comment by saulhidalgoaular** [comment]
Good afternoon. I have fixed the bug you have mentioned @IanMayo . Solution is in this PR.
https://github.com/debrief/debrief/pull/4096
but, well, `4079_graph_disposal_for_invalid_selection` can be tested with non-rep file normally.

**Comment by helenayele** [comment]
I saw the issue last time and I filed it at #4073

**Comment by saulhidalgoaular** [comment]
> I saw the issue last time and I filed it at #4073

I am checking it @helenayele

**Comment by saulhidalgoaular** [comment]
@helenayele You are probably running the test on `4079_graph_disposal_for_invalid_selection`. It contains only the changes mentioned on this branch.
To find the branch with the fix for #4073, the PR is this https://github.com/debrief/debrief/pull/4096
They are all merged into `develop` tho. It can be tested there.

**Comment by helenayele** [comment]
ah, sure, @saulhidalgoaular   , I know it is merged in the develop, but I tried to answer for Ian's question, I saw the issue that rep files doesn't load their tracks in the select tracks combo last time and filed it. for sure I tested that in the  first graph branch.

**Pull request merged**
