### PR TITLE
Issue #1343 - Switch to manually generated PDF tutorials

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
@pecko - would you mind changing the PR so that we keep the cheat-sheets XML files, the DITA-map files, and the Ant file to actually do the generate?

This will save us some time/effort if we ever wish to reinstate them (they represent a large investment in innovation).

But,  I would like you to comment out / remove build file lines so that we don't pull in pdftk or actually trigger the cheat sheet Ant build file.

cheers,
Ian

**Comment by pecko** [comment]
OK. I will change the PR later. Is that urgent?

**Comment by IanMayo** [comment]
No, not urgent.

thanks.

**Comment by IanMayo** [comment]
Hey, the changes look like just what I was looking for.

**Pull request merged**
