### PR TITLE
5051 orm performance improvement

### LINKED ISSUE #5051: Pepys import performance
I'm importing a datafile with 4 points:
image

The data takes 9 seconds to load:
screencast
It would be useful to understand what is happening in this time, and to see if any bottlenecks can be resolved.

We do have our licences for Yourkit Java Profiler, if you think that will help.

This larger file (10k) points takes 14 seconds to load:
image

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #5051

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Good morning @IanMayo .

There is something I saw that I would like you to confirm it is conceptually correct.

In the bug https://github.com/debrief/debrief/issues/4894 , I realized that the grid was trying to insert an Item with the same time stamp (because it was a copy of one of the items), so it was throwing an exception. So, I have created the class `FixWrapperCollisionCheck` to modify the item that is being inserted, changing the time by adding 1 second in case it has the exact same time. All good.

However, I have found in the sample database some datafiles that contains Fixes with the exact timestamp. Currently the `FixWrapperCollisionCheck` interprets it like an error, and "correct" it by adding 1 second later to the fix. Is this behavior the expected? CAME2_UK has 11521 repeated timestamps, which are being added with a difference of +1 sec.

Debrief without the CollisionCheck would simply ignore the insertion.

**Comment by saulhidalgoaular** [comment]
oh @IanMayo , I didn't mention it, but the import time has been reduced from 7 minutes to 1.2 seconds.

**Comment by IanMayo** [comment]
> oh @IanMayo , I didn't mention it, but the import time has been reduced from 7 minutes to 1.2 seconds.

WHAT?  7 minutes to 1.2 seconds!  wow!

**Comment by IanMayo** [comment]
> CAME2_UK has 11521 repeated timestamps
I thought that track was only around 11521 points long

Anyway - I'm happy with your strategy in general.  But, could we add one millisecond instead of one second?

For a track with one second updates, the handler will end up incrementing the time of every point.  Aaah, that would make it look like there were 11k duplicates 🤣

**Comment by saulhidalgoaular** [comment]
Hello @IanMayo .

Sorry, I was wrong, I wasn't adding 1 second, I was adding 1 millisecond already.

**Review by IanMayo — APPROVED** [review]
Amazing improvement, thanks @saulhidalgoaular

**Pull request merged**
