### PR TITLE
4517 class exception draganddrop

### LINKED ISSUE #4517: ClassCastException is thrown while changing the filled and semi-transparent properties of SensorArc
While changing the properties of SensorArc like filled and Semi-transparent properties, ClassCastException is thrown.
[ClassCastException_cannot cast to baseLayer.txt](https://github.com/debrief/debrief/files/3646613/ClassCastException_cannot.cast.to.baseLayer.txt)

### Steps to reproduce

1. Open boat1.dpf
[boat1.zip](https://github.com/debrief/debrief/files/3646618/boat1.zip)
2. From fwd dynamic(40 items) , Change the semi-transparent or filled properties to YES, if it was No, or change to No if it was Yes
3. Do the same for all items.
4. See that the above ClassCastException is thrown.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4517

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Please, don't merge until I go a bit deeper in this ticket.

**Comment by saulhidalgoaular** [comment]
Ok. I have found the reason of this. What was happening is that a sensor was getting dragged into another sensor.
This patch is valid for this case (and other more), because it checks if the destination of the drag is a BaseLayer.

I _think_ it is ready for testing/merging.

**Comment by IanMayo** [comment]
Thanks for that @saulhidalgoaular .  Do you mean a `SensorArc` was being dragged onto another one?

**Comment by saulhidalgoaular** [comment]
@IanMayo Yes. Exactly.

**Pull request merged**
