### PR TITLE
4636 Switch GeoTools to new lib

### PR DESCRIPTION
**Pull request by IanMayo**
Supports first part of #4636

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - it's an existing problem with OpenJDK11 for JFreeChart:
http://www.jfree.org/forum/viewtopic.php?t=120416

**Comment by helenayele** [comment]
And also maximize button doesn't maximize D-Lite on the available screen width. See the below video
[Image from Gyazo](https://gyazo.com/550a96454b37f6d72b61dce220fbee1d)
When I select maximize button D-Lite should be expanded and fill all the available screen space.

**Comment by IanMayo** [comment]
Thanks @helenayele - could you create issues for them both please - labelled as Debrief-Lite.

**Comment by IanMayo** [comment]
@helenayele - there's a good chance we'll find other Java11 issues with Debrief Lite, lots libraries have updated as part of J11.

But, let's merge this PR, and start finding the other issues.

**Pull request merged**
