### PR TITLE
4094 updated eclipse to latest (2019-06)

### PR DESCRIPTION
**Pull request by theanuradha**
A step forward in #4094

### CODE REVIEW

**Comment by IanMayo** [comment]
@theanuradha - I've re-run the build, but it's still failing.

**Comment by IanMayo** [comment]
Thanks @theanuradha ,  I've just had a play with a 2019_06 build it seems to run ok.  The only thing I've found that doesn't work is we don't see the rubber band as we zoom in on the plot.

**Comment by theanuradha** [comment]
> Thanks @theanuradha , I've just had a play with a 2019_06 build it seems to run ok. The only thing I've found that doesn't work is we don't see the rubber band as we zoom in on the plot.

@IanMayo can you create an issues with steps .

**Comment by IanMayo** [comment]
> > Thanks @theanuradha , I've just had a play with a 2019_06 build it seems to run ok. The only thing I've found that doesn't work is we don't see the rubber band as we zoom in on the plot.
> 
> @IanMayo can you create an issues with steps .

* open application
* open `boat1.rep` from Navigator
* multi-colored track will appear, on a white background
* zoom in on an area, using mouse-drag
* while the zoom works, the rubber-band that shows the area while mouse-dragging doesn't appear

**Comment by IanMayo** [comment]
This PR is quite a large change to our infrastructure.  It's a stepping stone to updating Java to 11.  But, this PR just covers updating Eclipse.

We should give it a good test, then get it merged.  I'd appreciate the support of @ayeshare , @helenayele  and @saulhidalgoaular  in doing this.  It's right for us all to get up to date.

To test it, do the following:
* download/unpack Eclipse 2019_06  (_Eclipse IDE for RCP and RAP Developers_)
* import Debrief
* open `org.mwc.targetplatforms \ eclipse-latest.target`
* click on `Set as target platform` - at the top right (it may take a few minutes to run)
* open `org.mwc.product \ debriefng.product`
* click on `Launch an Eclipse application`

Debrief will load.  Do some general testing - see how things work...

**Pull request merged**
