### PR TITLE
4181 lite tote

### LINKED ISSUE #4181: Tote Information is outdated when tracks are deleted
Steps to reproduce are here:
https://github.com/debrief/debrief/pull/4154#pullrequestreview-236502867

After deleting a track from the Outline view, the Normal Highlighter continues to render it.

~~Plot highlighters are still getting rendered, and also primary/secondary tracks are getting outdated after deletion.~~
Also please handle https://github.com/debrief/debrief/pull/4154#issuecomment-493903284 on this PR.

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #4181

### CODE REVIEW

**Comment by IanMayo** [comment]
Morning @helenayele - thanks for catching that.  I'm not that familiar with the xy-graph (yet), I'll investigate it.

**Comment by IanMayo** [comment]
Aah, err, @saulhidalgoaular - I think I've broken the XY Graph, when it comes to deleting tracks.

I think the Plotter/Highlighter and the XY Graph may both be looking at the same list of tracks.  I'd appreciate you investigating if/how I've broken the graph. If this isn't fixable, I'd appreciate you investigating an alternate strategy for #4181

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele . It looks like it is working as expected. Please, feel free to test it to confirm it.

**Comment by helenayele** [comment]
Now after deletion of a track from outline view while it is playing in the time control, no highlighter is shown and looks like this :
[Image from Gyazo](https://gyazo.com/dafd02a0f642326dc36dd11ee7a999f4)

**Pull request merged**
