### PR TITLE
3826 openplot errorhandling

### LINKED ISSUE #3826: Provide user friendly Info when user tries to open invalid files
When I try to open Rep files using **Open Plot** action , it displays these dialogs in ascending order .

1. [Image from Gyazo](https://gyazo.com/7c4e31bb65319acc17746379580f6fd4)

2. [Image from Gyazo](https://gyazo.com/117462fc0890310827aa902cf31d1fb2)

For some of the Rep files the first dialog may not be shown but the 2 one is common for all. 
### Expected Result:

1. No multiple error dialog should be shown for the user -  A Single error dialog should be seen
2. The file name should not be loaded in the title bar
3. Should not silently logged exception it should show the problems in dialog 
4. It would be very cool if we  provide user friendly message to our users.

### PR DESCRIPTION
**Pull request by ayeshare**
fixes #3826

### CODE REVIEW

**Comment by IanMayo** [comment]
@ayeshare - the static analysis is complaining about you throwing the RuntimeException.

Instead of doing that, could you store _toolParent in a final local field, then call  `_toolParent.logError()`.  We don't do much error handling currently, but at least we'll handle all the errors in one place.
thx.

**Comment by IanMayo** [comment]
@ayeshare - this PR seems to have mixed commits, since it includes adding the shapefile.

Since it only needed a minor code change, and since it's got a code conflict to resolve, would you mind re-implementing it in a new PR off `develop` please?

**Comment by ayeshare** [comment]
> @ayeshare - this PR seems to have mixed commits, since it includes adding the shapefile.
> 
> Since it only needed a minor code change, and since it's got a code conflict to resolve, would you mind re-implementing it in a new PR off `develop` please?

will do

**Comment by IanMayo** [comment]
@ayeshare - I'm not quite sure where we got to with this.

Has the work been transferred to another branch?

**Comment by IanMayo** [comment]
Closing this PR, @ayeshare working on different branch.

**Pull request closed without merging**
