### PR TITLE
4652 - reinstate Pan action

### PR DESCRIPTION
**Pull request by ayeshare**
fixes #4652 

removed system.out statement

added back commented code for pan action

### CODE REVIEW

**Comment by IanMayo** [comment]
@ayeshare  - this doesn't look related to #4652 . Have you got the number wrong?

**Comment by IanMayo** [comment]
@ayeshare - this doesn't appear to resolve issue #4652 . Could you double-check?

**Comment by ayeshare** [comment]
> @ayeshare - this doesn't appear to resolve issue #4652 . Could you double-check?

This doesnt resolve the issue, but I found that in Pan command setting cursor tool part of the code is commented out. So I added it back.  this is needed

**Comment by helenayele** [comment]
The behavior before the fix and after applying this fix are the same: See the below videos :
Before 
[Image from Gyazo](https://gyazo.com/0ffe264092b16f33ddb1dc837ebc80c5)

After 
[Image from Gyazo](https://gyazo.com/6b7f51f01042170283f0ba02f039f339)

**Comment by IanMayo** [comment]
@helenayele - are you saying that Pan was already working?

**Comment by IanMayo** [comment]
(PR renamed, to describe what it represents)

**Comment by helenayele** [comment]
Yes, Ian, It was working before the fix, and I don't get any difference before and after the fix.

**Comment by IanMayo** [comment]
The code that @ayeshare  put back in does special handling for `MouseEvent.BUTTON3`

@ayeshare - can you remember why we required that code?

**Comment by IanMayo** [comment]
Closing, appears underlying issue no longer present.

**Comment by helenayele** [comment]
yes - pan action works

**Pull request closed without merging**
