### PR TITLE
Issue 1871 Ktable to JFace Viewer 

### LINKED ISSUE #1871: Switch Narrative viewer from KTable to JFace table
The narrative viewer was introduced before the JFace Table was introduced, if I remember correctly.

If it's not too complex a task, I'd like us to switch the view to use a JFace table control.

These parts of the UI functionality should be present in the new implementation - please indicate if any aren't possible:
* [ ] double-click on *Source*** or **Type** header to open dialog to filter on that field
* [ ] entries color coded according to the narrative entry color
* [ ] optional word-wrap
* [ ] two-way sync, select row according to current time, set current time when row double-clicked

### PR DESCRIPTION
**Pull request by theanuradha**
Fixes #1871 

image

Pending is word wrap as it is not supported by default looking at workarounds

### CODE REVIEW

**Comment by theanuradha** [comment]
@IanMayo I assume we can merge it now 

image

**Comment by theanuradha** [comment]
Will test on Linux as well

**Comment by IanMayo** [comment]
Works great on Linux!

**Comment by theanuradha** [comment]
@IanMayo ok I can move to search option now maybe we can merge to master

**Comment by IanMayo** [comment]
Sure, let me just do a bit more checking.

**Pull request merged**
