### PR TITLE
4043 automatically expand collapsive panel

### LINKED ISSUE #4043: Automatically Expand Collapsive Behavior without Doubleclicking.
Collapsive Panels now need to be unfolded to enable the dragging process. It would be good to drag a collapsed panel, uncollapsing it automatically.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4043

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
CI tests gave
java.net.ConnectException: Connection refused (Connection refused)
[INFO] Process terminated. Send shutdown request to RCPTT runner.
but it all should be fine, since the change is not relate with Full Debrief.

**Comment by IanMayo** [comment]
@saulhidalgoaular - when I ran this branch, I expected to see a collapsed graph panel that could be dragged to open.

But, it shows an already expanded graph panel.

Could you remind me what I should expect?

**Comment by saulhidalgoaular** [comment]
Good morning @IanMayo . The thing is that the collapsed panel is only part of the branch `3924_graph_toolbar`. This branch allows you to drag directly a panel even if it is collapsed. Steps to test:

1. Open Debrief Lite
2. Fold the Graph Panel.
3. Drag it when collapsed. It should open again, without need of double clicking.

**Comment by IanMayo** [comment]
Thanks for that @saulhidalgoaular 

I _don't quite_ get the described behaviour.  If I drag the panel to minimise it, then I can drag it to expand it.

But, if I double-click to collapse it, then I can only expand it by double-clicking again.

Hopefully this shows it:
https://youtu.be/bcf3JzfAClU

**Comment by IanMayo** [comment]
Ok, merging - to prevent conflicts.

**Pull request merged**
