### PR TITLE
Issue #1163 - Strange UNDO problem on opening plot

### PR DESCRIPTION
**Pull request by pecko**

### CODE REVIEW

**Comment by IanMayo** [comment]
Quick piece of feedback - making edits from the Outline View (such as changing a track color) aren't being added to the undo history.

On first impressions, the Undo problem doesn't seem fixed, but I'll investigate more to see if I can see a pattern.

**Comment by pecko** [comment]
I haven't tested the Outline view. Will check...
The PR separate Undo/Redo for each editor's instance. 
IMO, it was main issue in previous code. For instance, you change color for the NELSON track in boat1.rep and get the same Undo action in boat2.rep that doesn't have the NELSON track. Also you keep Undo/Redo action when opening/closing editors.

**Comment by IanMayo** [comment]
Yes, the new behaviour is certainly more sensible.

If I remember correctly, the previous behaviour was implemented so that "Undo" would work when a view (not the editor) had focus.

Users would make an edit from the Outline view, then not be able to undo it until they gave focus to the editor.  They found this non-intuitive.

**Comment by pecko** [comment]
I will check, but Undo worked when a editor had focus. For instance, you can right-click a track in editor area and change track's color. I have followed your case this way (without the Outline view).

> Users would make an edit from the Outline view, then not be able to undo it until they gave focus to > the editor. They found this non-intuitive.

Agree, but it would be good that the actions in the Outline view be undoable/redoable. We can make a separate undo/redo actions in the Outline view, but I have to check. These actions should be active (doable) when the focus is in the Outline view or corresponding editor.

**Comment by IanMayo** [comment]
> These actions should be active (doable) when the focus is in the Outline view or corresponding editor.

Yes, exactly.  Undo operations should apply to the current editor, even if the editor isn't the currently selected RCP pane.

**Comment by pecko** [comment]
Could you please check the actions in editor, for now. I will check the Outline view.

**Comment by IanMayo** [comment]
Hey - the Two-click undo problem issue is fixed in this branch!

**Pull request merged**
