### PR TITLE
#1703 added key binding

### PR DESCRIPTION
**Pull request by theanuradha**
context

### CODE REVIEW

**Comment by IanMayo** [comment]
I see the shortcuts on the menu item, but none of them are working for me (Eclipse 3.8.2, Ubuntu 15.10)

Steps to reproduce:
* open **shapes.dpf**
* open **Annotations** layer in Outline view
* select first item
* press *delete* key
* nothing happens.

If I right-click and select Delete, it gets deleted, it's just the key that doesn't work.  

Copying shapes from **shapes.dpf** to the **Annotations** layer in **sample.dpf** doesn't work either.

**Comment by theanuradha** [comment]
@IanMayo I will look in to it.

**Comment by theanuradha** [comment]
@IanMayo  to get key command without right click we need to provide command handlers activate on selection of element. 

Shall I go ahead and support this ?

**Comment by IanMayo** [comment]
Hi there @theanuradha.

Providing the shortcut only when the menu is open isn't a satisfactory implementation- once the user has used the mouse to right-click on an item, it will almost always be easier to then use the menu item to cut/copy/paste. 

So, please investigate permanently providing the shortcuts when an item is selected in the Outline view.  

To start with, please just investigate this.  It's a minor feature that wouldn't justify extensive code changes.

**Comment by theanuradha** [comment]
@IanMayo  I have investigated and added to Outline view to copy,cut & delete. Code change was not big I refactor and re-use code to do the real operations and make sure the wire correctly to same action.

**Comment by IanMayo** [comment]
Ok, we still need the "Paste" functionality.

I can use <ctrl>-x to cut an item, but I have to right-click to "Paste" it into a new layer.  Could you add the shortcut to the Paste operation?

**Comment by theanuradha** [comment]
@IanMayo  Im on it

**Comment by theanuradha** [comment]
@IanMayo paste action key binding support added.  
on **master branch** i found a NPE on paste will create a issue separately as it is not related to this.

**Comment by IanMayo** [comment]
Ok, paste working.

[I may have fixed the NPE you found: https://github.com/debrief/debrief/pull/1735/commits/e8d8d7322735aac8ecb23d6df4d1c312e2d9980f]

I'm not seeing the shortcut shown against the menu item for "Paste":
paste_shortcut

Aah, another issue.  I have two plots open, and the shortcuts appear to only work on one of them.

Steps to reproduce:
* open **sample.dpf** and **shapes.dpf**
* switch to **sample.dpf**
* open **Misc (5 items)**
* select first 3 items
* press Ctrl-C
* switch to **shapes.dpf**
* select **Annotations**
* Press Ctrl-V
* Nothing happens - *the items should have pasted*
* Right-click on **Annotations**
* Select **Paste 3 items**
* Items pasted
* Switch back to **sample.dpf**
* Still have 3 items selected in **Misc (5 items)**
* Press Ctrl-X (to cut)
* Nothing happens *the items should have been cut*

It looks like we have an "active editor" assigned.  Doing a manual cut/copy/paste sets the current editor to be "active", which makes it receive the keystrokes, but it doesn't change when we manually switch plots.

**Comment by theanuradha** [comment]
@IanMayo  OK will get to this

**Comment by theanuradha** [comment]
@IanMayo  I have added "shortcut shown against the menu item for "Paste":"

about second issue Im trying to sort it seems outline view not correctly activate when switch. if you select outline view by tab header it works. bit strange i'm investigating.

**Comment by theanuradha** [comment]
@IanMayo  I have push fix, now multi plot editor works correctly and all key bindings correctly connect

**Comment by IanMayo** [comment]
Great - well done @theanuradha

**Pull request merged**
