### PR TITLE
3939 Close button.

### LINKED ISSUE #3939: Introduce "Close" button, and "Closed" state
We wish to allow a user to Close the current document.

The handler for this should invite the user to save the plot (if necessary).  

Then the map pane will be hidden, the Outline will be emptied, and the Graph cleared.  All plot-related controls should be disabled.

Clicking on Open, New or Import should re-enable plot-related controls.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #3939

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Good morning. I am not sure of the difference between hiding the map, and clearing the graph. Currently on this branch, after closing the document and saving it or skipping the saving, Debrief ends up like just opened.

**Comment by IanMayo** [comment]
@Saul - I fixed a static analysis issue:
https://app.codacy.com/app/IanMayo/debrief/pullRequest?prid=3354053

(`ctrl-shift-o` -> `optimise imports`)

**Comment by IanMayo** [comment]
@helenayele  - I had to modify some code as I fixed conflicts for this. Would you re-check it, please?

**Comment by saulhidalgoaular** [comment]
> @saul - I fixed a static analysis issue:
> https://app.codacy.com/app/IanMayo/debrief/pullRequest?prid=3354053
> 
> (`ctrl-shift-o` -> `optimise imports`)

oh, ok, ok.

**Pull request merged**
