### PR TITLE
blank progress dialog on import replay/dpf file

### LINKED ISSUE #4190: blank progress dialog on import replay/dpf file
see the last comment on 
https://github.com/debrief/debrief/issues/3809#issuecomment-492619262

The issue is that the progress dialog is showing up as blank dialog with nothing displayed.  The progress monitor was displaying correctly before we introduced the ribbon for the toolbar.
The ribbon requires we launch the app, asynchronously, therefore SwingUtilities.invokeLater() is used.  

Steps to reproduce:
Open or drag/drop a large rep file such as `Bulk_red_tracks.rep` from sample_data.

The progress dialog popsup which shows a blank dialog.

I tried using SwingWorker to import the rep file, this works only in the case of narratives replay file as there are no ui calls. Running the import (reading file) process in background, showed the progress dialog correctly.

### PR DESCRIPTION
**Pull request by theanuradha**
Fixed #4190

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - could you please check that this fixes #4190 ?

**Comment by helenayele** [comment]
sure Ian checking it

**Comment by IanMayo** [comment]
@helenayele - I _think_ that's unrelated. I'll investigate it.

**Comment by IanMayo** [comment]
@helenayele - let's investigate that Array Index Exception in another issue, once this is merged.  

The line numbers don't seem to match up with my code for this branch. Let's merge it, and we'll be working off the `development` branch.

**Pull request merged**
