### PR TITLE
3826 open plot error 4 (Develop)

### PR DESCRIPTION
**Pull request by IanMayo**
Additional changes in DebriefLiteApp for correct file import.

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - next week could you check this PR please?

It _should_ have the correct processing for displaying errors on loading bad content, and not updating the application title bar if loading fails.

**Comment by IanMayo** [comment]
@helenayele - when you get chance, could you provide me with versions of the sample data-files you used above?

**Comment by helenayele** [comment]
I have used sample_data folder from debrief Version: 3.0.473
Build id: 20190328
Build date: 2019-03-28
And I make the invalid file by removing some lines and column of valid dpf files.

**Comment by IanMayo** [comment]
Sure @helenayele - here they are:
[bad_tracks.zip](https://github.com/debrief/debrief/files/3083505/bad_tracks.zip)

They are in the `sample_data\other_formats` folder for this branch (and the related branch off `master`).

**Comment by helenayele** [comment]
I have tested the above attached  rep and dpf files , and for the rep I don't see any more dialog but for the dpf file, I get 2 dialog
 - [Image from Gyazo](https://gyazo.com/5db1396ae62099d6f27ab761dfef6778)

**Comment by IanMayo** [comment]
@helenayele - I think you've indicated that this isn't complete. But, I'm keen to merge it, to avoid conflicts. 

If there's anything outstanding, could you create it as a new issue please?

**Comment by helenayele** [comment]
Sure, I will re-test in develop branch and file if there is any issue.

**Pull request merged**
