### PR TITLE
Issue #1169 - Use of Nebula chart widget instead of JFreeChart

### PR DESCRIPTION
**Pull request by pecko**
Step One - integrate the nebula graph control into the build

### CODE REVIEW

**Comment by IanMayo** [comment]
Given the success of our use of the SWT version of JFreeChart, I think we no longer need this nebular chart.  Right?

**Comment by pecko** [comment]
I think so.

**Comment by IanMayo** [comment]
Aah no, let's keep it. 

I'll need to check the SWT JFreeChart with my users who were experiencing the JFreeChart freezing problem (#1169)

**Comment by pecko** [comment]
OK. It's just this PR, that is, adding required nebula plugins.

**Comment by IanMayo** [comment]
Sure.  If the SWT JFreeChart  introduces a problem then we will persevere with this PR.

**Comment by IanMayo** [comment]
IAN - DON'T MERGE THIS, IT IS NO LONGER NECESSARY.  The SWT version of JFreeChart worked just fine.

**Pull request closed without merging**
