### PR TITLE
3845 disable time on reset

### LINKED ISSUE #3845: Time player is enabled after resetting
### Steps to Reproduce:

1. load boat1.rep
2. See the time menus - they are enabled and ready to play
3.  Select New Action from  File menu - Don't save it
4. Now the map has no any track and empty 
5. Select Time menu and see that all the time player menus are enabled and click Play
it is playing
[Image from Gyazo](https://gyazo.com/a951b1e36a909c9875399b72eaa91681)

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #3845

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - hopefully I've fixed this.

**Comment by IanMayo** [comment]
@helenayele - are you happy that this one is complete?

**Comment by helenayele** [comment]
The start and end dates on Time filter are not visible until I click on this filter, Please see this, I think it needs some refreshing. 
[Image from Gyazo](https://gyazo.com/01b562d0346dad0ce98410b4b8bb61b6)
This issue only exist if the user opens the same file before resetting or when the user doesn't modify those filter values before resetting.

**Comment by IanMayo** [comment]
Ok, I've had a play. I can reproduce it, but can't resolve it quickly.

**Comment by IanMayo** [comment]
Merging early, to let features get tested at trial next week.

**Pull request merged**
