### PR TITLE
3826 open plot error 3

### PR DESCRIPTION
**Pull request by IanMayo**
Attempt minimal set of steps necessary to correctly handle D-Lite import failure.

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - does this branch contain the same dialog-related problems as #4025?

**Comment by helenayele** [comment]
No it doesn't contain such dialog related issues.

**Comment by IanMayo** [comment]
@helenayele - can you remember which bad data file silently opened?

**Comment by helenayele** [comment]
sure this is the dpf file that opened silently - 
[boat2_eee.zip](https://github.com/debrief/debrief/files/3079967/boat2_eee.zip)

**Comment by IanMayo** [comment]
Aaah, @helenayele - this is the `master` branch, which is deliberately behind `develop` when it comes to DebriefLite.

You only need to test Full Debrief from this branch.

**Comment by helenayele** [comment]
So @IanMayo  what are the changes  in the full debrief due to this PR ?

**Comment by IanMayo** [comment]
Morning @helenayele  :-)  The changes will affect loading `.rep` and `.dpf` files - both by drag and drop or using the `File` menu.

**Comment by helenayele** [comment]
But @IanMayo  can we stop loading the file on full debrief if it is invalid file. Currently it loads the file even if it is invalid - [Image from Gyazo](https://gyazo.com/e1a53fb5306d09d7c16835dc8f1fb684) ?

**Comment by IanMayo** [comment]
@helenayele - I think it loaded the first 6 points - since the problem was only on line 7.  I _think_ It's the same for a similarly broken file in D-Lite.

**Comment by helenayele** [comment]
Yes , D-Lite also tries to load - it behaves the same as of  Full Debrief.

**Pull request merged**
