### PR TITLE
3683 loading dynamic layers in d lite

### LINKED ISSUE #3683: Dynamic Shape Handler needs to move plugin
`DynamicShapeLayerHandler` and `DynamicShapeHandler` are currently in org.mwc.debrief.core

That means they can't be referred to from `Lite`.

More them to Debrief.legacy.

In full Debrief they're loaded by extension in the `plugin.xml` - we should explicitly register them in `DebriefLiteApp`

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #3683 

This fix allows boat1t.dpf to be loaded.  Once loaded, you will see the time displayed in two places on the plot.

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - while this PR prevents the warnings when loading those files, it doesn't correctly plot the time label in `boat1t.dpf`.

That has been captured in a separate issue - #4009

**Comment by helenayele** [comment]
@IanMayo  does it support to open dynamic shapes like arc, rectangle,etc

**Comment by IanMayo** [comment]
@helenayele - you gave a list of failing files here:
https://github.com/debrief/debrief/issues/3697#issuecomment-480796373

**Comment by IanMayo** [comment]
@helenayele - yes, it can load `boat_1_2_arcs.rep`.

The dynamic shapes load (we can verify it from the Outline). But, the rendering still needs to be fixed.

**Comment by helenayele** [comment]
Yes from outline view the dynamic shapes are fully loaded but they are not loaded in the map. sure will wait the fix

**Comment by IanMayo** [comment]
@helenayele - I'm deferring that fix. It has external dependencies.

**Pull request merged**
