### PR TITLE
make sure import dialog stay on top

### PR DESCRIPTION
**Pull request by theanuradha**
@IanMayo  Progressbar dialog is coming from Swing **ProgressMonitor** in MWC.Utilities.ReaderWriter.ReaderMonitor we can not change in unless we have to use new impl of progress dialog in swt

### CODE REVIEW

**Comment by IanMayo** [comment]
@theanuradha - could you apply this fix to any other SWT dialogs that we open?

**Comment by theanuradha** [comment]
@IanMayo  Sure I will check all

**Comment by theanuradha** [comment]
@IanMayo  I only fount any other place use Dialog is **CoreFreqImportDialog**

**Comment by theanuradha** [comment]
image


image

**Pull request merged**
