### PR TITLE
4815b alternate approach

### LINKED ISSUE #4814: Pepys Database Import - PostGres support
The _target_ database for this system will be a networked PostGres database.

We need Debrief to be distributed with the jars to support both PostGres and SQLite.

Ian will provide @saulhidalgoaular  with the connection details for an Internet-hosted PostGres database that contains this data.

We should verify that we can populate the UI from this database.

### LINKED ISSUE #4826: Pepys - SQL-error or missing database error while trying to import data
After selecting 'Import from Database button', I get a wizard that imports data from db. But after I select my time period and the rest attributes and select Apply, it throws an error dialog that stated that database is missed. But the database is found in pepys project like this :
[Image from Gyazo](https://gyazo.com/5291e16fc5bdddb85b5933b973d99d41)

[Image from Gyazo](https://gyazo.com/3b4f0629e3680d37f66e2e97e1f25625)
Stack Trace:
Query: SELECT NTP.state_id AS NTQ, NTP.time AS NTR, NTS.sensor_id AS NTT, NTS.name AS NTU, NTV.sensor_type_id AS NTW, NTV.name AS NTX, NTY.platform_id AS NTZ, NTY.name AS NUA, NTS.created_date AS NUB, NTP.heading AS NUC, NTP.course AS NUD, NTP.speed AS NUE, NUF.datafile_id AS NUG, NUF.simulated AS NUH, NUF.privacy_id AS NUI, NUJ.datafile_type_id AS NUK, NUJ.name AS NUL, NUJ.created_date AS NUM, NUF.reference AS NUN, NUF.url AS NUO, NUF.created_date AS NUP, NTP.privacy_id AS NUQ, NTP.created_date AS NUR, X (NTP.location) as NUS_X, Y (NTP.location) as NUS_Y, Z (NTP.location) as NUS_Z FROM States AS NTP INNER  JOIN Sensors AS NTS ON NTS.sensor_id = NTP.sensor_id INNER  JOIN SensorTypes AS NTV ON NTV.sensor_type_id = NTS.sensor_type_id INNER  JOIN Platforms AS NTY ON NTY.platform_id = NTS.host INNER  JOIN Datafiles AS NUF ON NUF.datafile_id = NTP.source_id INNER  JOIN DatafileTypes AS NUJ ON NUJ.datafile_type_id = NUF.datafile_type_id WHERE '2000-03-23 13:25:15.000000' <= NTP.time AND NTP.time <= '2020-03-23 13:25:15.000000'
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (The specified module could not be found.
)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)

### PR DESCRIPTION
**Pull request by IanMayo**
Supports #4815 
Fix #4826 
Fix #4814

### CODE REVIEW

**Comment by IanMayo** [comment]
Well, @saulhidalgoaular - I've had a go, and have a method that only calls `createInstance` from one place. But, I can't say it's actually any better. It's certainly longer!

**Comment by IanMayo** [comment]
Ooh, everyone is a critic 🤣 

image

**Comment by saulhidalgoaular** [comment]
> Well, @saulhidalgoaular - I've had a go, and have a method that only calls `createInstance` from one place. But, I can't say it's actually any better. It's certainly longer!

Good afternoon. It looks to me!!

**Comment by IanMayo** [comment]
@saulhidalgoaular - I've pushed a commit that introduces some earlier error checking, to help the user diagnose their connection problem.

Would you mind finishing off the code, by displaying the actual error messages?

**Pull request merged**
