### PR TITLE
added Custom Boolean Editor, where show Description correctly 

### PR DESCRIPTION
**Pull request by theanuradha**
I have added custom Editor , Default one works as up on selection it change the value so it make description hide (as value change event)  and unexpected edit of the value as just by click on property it change the value. I have added Check box to avoid those issues 
image

### CODE REVIEW

**Comment by IanMayo** [comment]
Sorry, I think it will confuse the users.  Do you know how boolean property editors work in the rest of Eclipse?

**Comment by theanuradha** [comment]
@IanMayo  it depends. some plugins has option with Checkbox and Label provider also show check Icon than "Yes,No" text. 

right now issue is current one in master soon as u select on Label of the property it switch the value . as other type editors it enable editor but not change value to user

**Comment by IanMayo** [comment]
Are you able to switch to always showing the checkbox icon?

**Comment by theanuradha** [comment]
@IanMayo yes i can do that

**Comment by IanMayo** [comment]
@theanuradha - there's another outstanding item here - always showing the checkbox icon

**Comment by theanuradha** [comment]
@IanMayo I try to show image but it has many issue with ui inconsistency (can not show OS specific checkbox images ).

SO I have go with Dynamic Drop-Down Option. upon selection it show the drop-down with values  and list box is visible automatically 

image

**Comment by IanMayo** [comment]
OK. It's not as easy to use as the toggle image.  But, if it's the only way for the property description to show, then that's what we'll have to do.

**Pull request merged**
