### PR TITLE
4444 NPE offset times - Option 2

### LINKED ISSUE #4444: NPE while opening offset_times.rep file
While loading 'offset_times.rep' from sample-data project, D-Lite throws Null pointer Exception with the below stack traces:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl$somePeriod.extend(StepControl.java:1223)
	at Debrief.GUI.Tote.StepControl.recalcTimes(StepControl.java:972)
	at Debrief.GUI.Tote.StepControl.addParticipant(StepControl.java:905)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:445)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
	at Debrief.GUI.Tote.AnalysisTote.setPrimary(AnalysisTote.java:409)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:85)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
	at Debrief.GUI.Tote.AnalysisTote.dataReformatted(AnalysisTote.java:772)
	at MWC.GUI.Layers.fireReformatted(Layers.java:1044)
	at org.mwc.debrief.lite.DebriefLiteApp$3.performOperation(DebriefLiteApp.java:668)
	at MWC.TacticalData.temporal.PlotOperations.performOperation(PlotOperations.java:162)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$SliderListener.stateChanged(DebriefRibbonTimeController.java:279)
	at javax.swing.JSlider.fireStateChanged(Unknown Source)
	at javax.swing.JSlider$ModelListener.stateChanged(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.setMinimum(Unknown Source)
	at javax.swing.JSlider.setMinimum(Unknown Source)
	at org.mwc.debrief.lite.gui.custom.RangeSlider.setMinimum(RangeSlider.java:112)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$LiteSliderControls.setToolboxStartTime(DebriefRibbonTimeController.java:178)
	at org.mwc.debrief.lite.gui.LiteStepControl.propertyChange(LiteStepControl.java:191)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at MWC.TacticalData.temporal.TimeManager.setPeriod(TimeManager.java:164)
	at org.mwc.debrief.lite.DebriefLiteApp$15$1.run(DebriefLiteApp.java:1369)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

But the same file is opened by full debrief without any issues.
[Image from Gyazo](https://gyazo.com/2cd55b44685de36fe548175f01ac2723)

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4444

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
> It still logs the below exception and the file is not opened fully as well:
> [Image from Gyazo](https://gyazo.com/cfdf7c2224ec432c15046f262eee758f)
> 
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> at MWC.GenericData.HiResDate.greaterThan(HiResDate.java:223)
> at Debrief.GUI.Tote.StepControl$somePeriod.extend(StepControl.java:1224)
> at Debrief.GUI.Tote.StepControl.recalcTimes(StepControl.java:973)
> at Debrief.GUI.Tote.StepControl.addParticipant(StepControl.java:906)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:445)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
> at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
> at Debrief.GUI.Tote.AnalysisTote.setPrimary(AnalysisTote.java:409)
> at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:85)
> at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
> at Debrief.GUI.Tote.AnalysisTote.dataReformatted(AnalysisTote.java:772)
> at MWC.GUI.Layers.fireReformatted(Layers.java:1044)
> at org.mwc.debrief.lite.DebriefLiteApp$3.performOperation(DebriefLiteApp.java:668)
> at MWC.TacticalData.temporal.PlotOperations.performOperation(PlotOperations.java:162)
> at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$SliderListener.stateChanged(DebriefRibbonTimeController.java:279)
> at javax.swing.JSlider.fireStateChanged(Unknown Source)
> at javax.swing.JSlider$ModelListener.stateChanged(Unknown Source)
> at javax.swing.DefaultBoundedRangeModel.fireStateChanged(Unknown Source)
> at javax.swing.DefaultBoundedRangeModel.setRangeProperties(Unknown Source)
> at javax.swing.DefaultBoundedRangeModel.setMinimum(Unknown Source)
> at javax.swing.JSlider.setMinimum(Unknown Source)
> at org.mwc.debrief.lite.gui.custom.RangeSlider.setMinimum(RangeSlider.java:112)
> at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$LiteSliderControls.setToolboxStartTime(DebriefRibbonTimeController.java:178)
> at org.mwc.debrief.lite.gui.LiteStepControl.propertyChange(LiteStepControl.java:191)
> at java.beans.PropertyChangeSupport.fire(Unknown Source)
> at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
> at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
> at MWC.TacticalData.temporal.TimeManager.setPeriod(TimeManager.java:164)
> at org.mwc.debrief.lite.DebriefLiteApp$15$1.run(DebriefLiteApp.java:1369)
> at java.awt.event.InvocationEvent.dispatch(Unknown Source)
> at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> at java.awt.EventQueue.access$500(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> at java.awt.EventQueue.dispatchEvent(Unknown Source)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.run(Unknown Source)

Hi. Please, check it again.

**Comment by helenayele** [comment]
Able to open `offset_times` file without any issues.

**Comment by IanMayo** [comment]
@helenayele - this PR is still saying you've requested changes.  Do you need any, or is it ready to go?

**Comment by helenayele** [comment]
I can open the file without any issues :
[Image from Gyazo](https://gyazo.com/44ad8916f04c6b68988ac71adf114224)
 I just requested the change before the modification

**Pull request merged**
