### PR TITLE
4341 collapse panels

### PR DESCRIPTION
**Pull request by IanMayo**
Supports #4341

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - so, it has a different icon depending upon if it's going to expand or collapse the panels.

Sure, that's possible.  But, the state of the panels can be seen.

Aah, there's another issue.  If the user presses "Collapse", then the icon will switch to 'expand'.  Imagine the user then drags the Outline open. The required behaviour for this is that if any panel is open when the button is clicked, they will all collapse.

So, right now, the icon is "expand" - but clicking on it will perform "collapse".  So, I think we need an icon that doesn't indicate state.

**Comment by helenayele** [comment]
Okay understood, can we have tool-tip please?

**Comment by helenayele** [comment]
While collapsing/expanding, if the narrative panel was collapsed before, it will be somehow hidden when we select collapse button.
[Image from Gyazo](https://gyazo.com/5767c20981f51ee50a05c55944353ed1)
### Steps:
1. Launch D-Lite 
2. Collapse Narrative panel 
3. Click Collapse/expand button multiple times -

**Comment by IanMayo** [comment]
@ayeshare - yes, this is incomplete.  But, I'm going to merge this PR as it is, to get customer feedback, then carry on in another PR.

**Comment by helenayele** [comment]
@IanMayo I think you should mean Me(@helenayele )?

**Pull request merged**
