### PR TITLE
implemented save button as a dropdown and other file ribbon tab changes

### LINKED ISSUE #3870: Updated File/Application menu
We have an updated UX for the `Application Menu` in D-Lite:
https://xd.adobe.com/view/b84612dd-e964-4322-699d-90574b10b452-ce77/

See also the re-organisation of the `File` tab on Page 2 of the UX design.

Hopefully the icon for the application menu will be a nice big Debrief icon.

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #3870

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @helenayele - yes, that's a good suggestion. The word `Plot` doesn't seem necessary there.  Let's do that.

**Comment by IanMayo** [comment]
Quick one for @helenayele - the `Save-as` icon has to be smaller, to make space for those three dots.

**Comment by helenayele** [comment]
Oh, clear , thanks

**Comment by IanMayo** [comment]
this seems ok to me, @helenayele ?

**Comment by IanMayo** [comment]
@helenayele - I had to make some changes during the merge operation.  

Could you check it's still valid?

**Comment by IanMayo** [comment]
Yes, Helen, I'll make the request.  But, could you file that as a separate issue, so I can merge this one?

**Pull request merged**
