### PR TITLE
added New Project Wizard and mask Project Dialog

### PR DESCRIPTION
**Pull request by theanuradha**
image

#on selection
image

(Please note this will show when **reset** Prespective )
image

### CODE REVIEW

**Comment by IanMayo** [comment]
@theanuradha - I don't understand the overlap between this new wizard & the New Project wizard we worked on last month:
https://github.com/debrief/debrief/pull/1787

Shouldn't we use the same code in both instances?

**Comment by theanuradha** [comment]
@IanMayo  we can Drop old Dialog and Always use this Wizard so no code duplicate

**Comment by IanMayo** [comment]
Ok, could you update the PR to include removing the old code?

Have fixed minor typo(s).

**Comment by theanuradha** [comment]
@IanMayo  Please review again I have removed old Dialog and port Wizard to reuse

**Comment by IanMayo** [comment]
Hi there,
I need another minor change, please.

The dialog includes a message explaining why a folder is needed.  But, when the dialog first opens, this message is hidden by an error message:
messagehidden

I'm not sure if/how you can do it, but could you remove the error detection as the dialog first opens? Then only trigger validation when the cursor (for example) leaves the location text box?

**Comment by theanuradha** [comment]
@IanMayo I think I can let me try this

**Comment by theanuradha** [comment]
@IanMayo  done

**Pull request merged**
