### PR TITLE
3811 step control properties window

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Supports #3811 
Not finished yet

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
> Good morning @IanMayo . Regarding this commit, I am prompting the properties editor for Display Mode, despite it doesn't have properties to edit. Do we keep this behavior? I have checked Debrief Legacy and it does the same.

oh. Nevermind. I just realized there are properties for the snail painter.

**Comment by saulhidalgoaular** [comment]
There is a weird behavior with options 'T+ 'SSS and 'T+ 'MM:SS' . It just doesn't assign the selected format. I checked and the same happens with Debrief Legacy. Is it expected?
image

**Comment by IanMayo** [comment]
Ah yes, that is a strange format.

It's for when the displayed time is meant be relative to some absolute time.   Imagine a simulated torpedo hitting a vessel.  The time of impact could be "T 00:00".  One minute before that would be "T -01:00" and one minute after would be "T +01:00". 

We no longer use the time label for this purpose though.  So, let's remove those formats from the listing.

Note: we now use the `Time Display (Relative)` UI element to do this time-zero style display of information:
image

**Comment by saulhidalgoaular** [comment]
Good mornigng @helenayele 

**Number 1:** Changes done.
**Number 2:** Removed unneeded formats.
**Number 3:** I think is depends mostly on the width of the application. For example, here I have a it with Font at 30.

Debrief Lite (22 Mar 17 20:24) - boat1 rep -_032

And here I have it with font size 5.

Debrief Lite (22 Mar 17 20:24) - boat1 rep -_033

I remember I saw an issue that defined the specific behavior when resizing for Debrief Lite.
I have changed the range as requested tho. Now the font size can be at most 20.

**Number 4:** I have seen this same behavior in Debrief Legacy. It shows the marker for other files tho (like sample.dpf). I can confirm if it is the desired behavior to check it deeper.

All this changes affect Debrief Legacy.

**Comment by saulhidalgoaular** [comment]
Hi @helenayele 
**Number 1** Removed Range option.
**Number 2** I cannot reproduce that. Do you have the steps to arrive to that state?

**Comment by saulhidalgoaular** [comment]
> Now small step is applied in the player's stepper.
> But we need to use uniform date format in our system. The edit properties use the below selected date format by default
> [Image from Gyazo](https://gyazo.com/92e9721cbb79e3d6ccdf400b7ac68bd6).

Hi @helenayele . I have added the default format to the properties editor and it is now selected by default.

**Pull request merged**
