### PR TITLE
upgrade to flamingo with geotools commented out

### LINKED ISSUE #4712: repaint issue on play icon in timecontroller tab
This issue is on branch https://github.com/debrief/debrief/pull/4603
there is a repaint issue on the play button.  At the end when the task is done, repaint works only when the whole frame repaints, not on its own. On mouseover or mouse click the image repaints.  I spent some time on this, but couldnt figure out.  I added a propertychangelistener to repaint and even that didnt work.

Steps to reproduce:
* open Debrief-Lite in branch `4562_upgrade_flamingo`
* load `boat1.rep`
* switch to `Time` tab in ribbon
* drag time-slider almost all the way to right (but leave some time remaining)
* press `Play` VCR button
* watch time move forward
* When time runs out, `Play` icon disappears (see video below).  Play button does repaint on mouseover

Expected: The play button image should be updated without the need for mouseover.

Screencast of issue

The code to update the command button is in DebriefRibbonTimeController.java#1125

### PR DESCRIPTION
**Pull request by ayeshare**
supports #4562
Fixes #4712 

Changes to upgrade to flamingo without geotools.

### CODE REVIEW

**Comment by helenayele** [comment]
Fixed once :
1. Background Transparency is working
2. Ctrl  + c - works

Issues 
1. Short-cut keys like ctrl +x , xtr +v and ctrl +delete  still don't work. Only ctrl + c - works
2. Issue number #3  "Save button (parent one) is not working, to save a file we have to click the Save item inside the combo box. " still reproducible.
3. Issue number #5 is still reproducible.
4. Issue number # 8 and 9 are still reproducible.

**Comment by ayeshare** [comment]
@helenayele 
>>Shortcut keys like ctrl + x, ctrl +c , ctrl + v, and ctrl +delete key , or delete key only for deletion are not working.

Please check if this is working on develop branch.  I havent changed these, might be a java ugrade issue

**Comment by helenayele** [comment]
> @helenayele
> 
> > > Shortcut keys like ctrl + x, ctrl +c , ctrl + v, and ctrl +delete key , or delete key only for deletion are not working.
> 
> Please check if this is working on develop branch. I havent changed these, might be a java ugrade issue

I have checked it and it works in develop branch without any issues , but it doesn't work in this branch.

**Comment by helenayele** [comment]
All the above issues are fixed except:

1. Ctrl + delete key or delete key do not remove a position from outline/Map panels . But able to remove shapes using those keys.
2. Stop button isn't seen immediately when it stops playing

**Comment by helenayele** [comment]
On current build, able to delete positions and shapes as well using ctrl + Delete or Delete keys.
And Play and stop buttons behaves correctly now e.x 
- When we modify time properties , if track was playing it will immediately stops playing 
- When we slides Filter to time start/end time, the play button doesn't remain hidden but it is very slow - the sliding process is very slow : See this
[Image from Gyazo](https://gyazo.com/a53337cb95afab0c55a0803f1c663b60)

**Comment by IanMayo** [comment]
@ayeshare - the new classes created in this PR could do with some tidying up.  There are many commented out blocks of code that should be removed.

The `Source` > `Clean up...` needs to be run on these new files, too.  The command should use the `configured profile` from the contribs directory (named `planetmayo`).

I can help you configure/run this, if necessary.

**Comment by helenayele** [comment]
The date format icon is now using the latest icon - [Image from Gyazo](https://gyazo.com/e99c13cd627972a847d5836f4c10a60d)

**Comment by helenayele** [comment]
The date-format icon now has got replaced with the latest one - [Image from Gyazo](https://gyazo.com/376a3f75df1f7923f62165682f7e50c9)

**Comment by helenayele** [comment]
@ayeshare  we need the fix to add the Rng/Brg measurement units as drop down please.

**Pull request merged**
