### PR TITLE
4850 Filtering on Server.

### LINKED ISSUE #4850: Pepys - text search
@saulhidalgoaular - can you confirm that the "free text search" is being run at the server, and not on the client?

That means...  the search string should be used in a SQL query that is run on the server.  We should not collect all the records, then filter them on the client.

### LINKED ISSUE #4854: Database import - UX feedback
@clenoble had a few suggestions on the design: 

1. The modal is quite small, and it might be difficult to find something once the list of items is very long with many levels all maximized. Ideally, when looking at any child, you should be able to see the top parent in the same screen (no scrolling)
2. The apply and import buttons on the other hand are quite big.
3. The modal title is too small: it should be bigger as it's the highest item in the information hierarchy. (edited) 
4. For the list, arrows replace the plus and minus signs I used in the wireframes. I find the arrows more confusing than plus and minus, especially at the lowest level when there is no children, do you still have an arrow but it's disabled? With a minus sign, you can be sure you have reached the bottom of the tree.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4850 
Fix #4854

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Good morning @IanMayo .

Currently this branch is doing the regular filtering on the server by a SQL generated, When the button Apply is pressed. (By the way, maybe it would be good to change the name "Apply" to "Search").

Coming back to the filtering process, I am not sure if it is good to remove the option of local filtering. Currently, It works like this:

1. We can write something in the filter search and we press "Apply"
2. A SQL is generated including the filtering search text, and it will bring only the desired results.
3. If you add more letters to the filter text after having the results, it will get filtered locally.

This behaviour certainly gives a very responsive application, but it could be confusing to the user, because it will work only on the data already queried when the "Apply" button was pressed.

If you prefer, I could remove this behaviour.

Thanks.
Saul Hidalgo.

**Comment by IanMayo** [comment]
@saulhidalgoaular - I've just spoken to @clenoble  about how we tidily support this search.

As you've indicated, the same search text is used in two ways:
* at first it's run on the server
* afterwards it's used to filter the downloaded data

This could be confusing.  A tidier way would be to include a "Text" panel on the left hand side.  This would just contain the single text box, that is used when "Apply" is clicked.

We then keep the search box above the listing, and that is just used to filter the displayed records.

(there was also feedback not related to the search form - I'll put that into a separate issue).

**Comment by IanMayo** [comment]
@helenayele - it would be good for you be familiar with what's happening here, and to play with text-search/filtering.

**Comment by IanMayo** [comment]
@helenayele  - as before, we need more details on what your `PEPYS_CONFIG_FILE` variable is, and to see the contents of that config file.  We need this to understand what type of database Debrief is configured to look at.

**Comment by helenayele** [comment]
Okay Ian , my connection environment variable points to the postgres.ini file downloaded last time. and its contents are :
[database]
db_type = postgres
db_username = pepysdb_dev
db_password = dev_P3pys
db_port = 5432
db_name = pepysdb_core
db_host = postgresql-pepysdb.alwaysdata.net

[Image from Gyazo](https://gyazo.com/af3ee23a32d781db0d5cfcab8ed75b1f)

**Comment by IanMayo** [comment]
Thanks @helenayele. Aah, is there anything useful/relevant in the error log?

@saulhidalgoaular - I've checked, and the always data server is up & running.

**Comment by helenayele** [comment]
Yes Ian the path is not correct I think, see this error log :
java.sql.SQLException: path to '/C:/debrief/debrief/C:/git/debrief/org.mwc.cmap.combined.feature/root_installs/sample_data/other_formats/pepys.sqlite': 'C:\debrief\debrief\C:' does not exist

see that there shouldn't be C:/git/debrief...in my case.
Because my debrief repository located at c:/debrief/debrief in my machine.

**Comment by IanMayo** [comment]
Aah, this looks like routine bug-fixing for @saulhidalgoaular.

**Comment by clenoble** [comment]
@IanMayo Here are my suggestions: Full text search in the filters on the left / Find in page on the right. 

To further differentiate the behavior between the two, when using find in page, I would only highlight relevant part of the page, rather than filtering further. This way, the user understands that the filters on the left (and only them) are still applied. 

Otherwise, the user will get confused if the "find in page" works apparently in the same way as applying a filter. 

Here are the wireframes: 
Debrief-Pepys-import-UI-01
Debrief-Pepys-import-UI-text-search-find-in-page

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele .

I have tried to reproduce the bug you have mentioned, but it is not reproducible. Maybe you have to restart Eclipse after changing the Environmental Variable, because It takes the value when Eclipse is opened.

**Comment by helenayele** [comment]
Okay Saul , I get Success while testing the connection, but it doesn't fetch the data it fails with the below error:
[Image from Gyazo](https://gyazo.com/4ac3b1720f0a481d8a23ecaefe161d8c)

Query: SELECT NTP.state_id AS NTQ, NTP.time AS NTR, NTS.sensor_id AS NTT, NTS.name AS NTU, NTV.sensor_type_id AS NTW, NTV.name AS NTX, NTY.platform_id AS NTZ, NTY.name AS NUA, NTS.created_date AS NUB, NTP.heading AS NUC, NTP.course AS NUD, NTP.speed AS NUE, NUF.datafile_id AS NUG, NUF.simulated AS NUH, NUF.privacy_id AS NUI, NUJ.datafile_type_id AS NUK, NUJ.name AS NUL, NUJ.created_date AS NUM, NUF.reference AS NUN, NUF.url AS NUO, NUF.created_date AS NUP, NTP.privacy_id AS NUQ, NTP.created_date AS NUR, NTP.location AS NUS FROM pepys."States" AS NTP INNER  JOIN pepys."Sensors" AS NTS ON NTS.sensor_id = NTP.sensor_id INNER  JOIN pepys."SensorTypes" AS NTV ON NTV.sensor_type_id = NTS.sensor_type_id INNER  JOIN pepys."Platforms" AS NTY ON NTY.platform_id = NTS.host INNER  JOIN pepys."Datafiles" AS NUF ON NUF.datafile_id = NTP.source_id INNER  JOIN pepys."DatafileTypes" AS NUJ ON NUJ.datafile_type_id = NUF.datafile_type_id WHERE '2000-04-23 07:33:41.000000' <= NTP.time AND NTP.time <= '2020-04-23 07:33:41.000000' AND ST_Contains(ST_GeomFromText('POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))'),NTP.location)
org.postgresql.util.PSQLException: ERROR: Operation on mixed SRID geometries
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2313)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327)
	at org.mwc.debrief.pepys.model.db.DatabaseConnection.listAll(DatabaseConnection.java:346)
	at org.mwc.debrief.pepys.model.tree.TreeBuilder.buildStructure(TreeBuilder.java:68)
	at org.mwc.debrief.pepys.model.ModelConfiguration.apply(ModelConfiguration.java:109)
	at org.mwc.debrief.pepys.controller.PepysImportController$8$1.run(PepysImportController.java:237)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by IanMayo** [comment]
Sorry @saulhidalgoaular - you have some merge conflicts to resolve here :-(

**Comment by IanMayo** [comment]
Ok, we need @helenayele  to have another play with the branch, now that the conflicts are resolved.

**Pull request merged**
