### PR TITLE
get UI back working on Multipath analysis view

### LINKED ISSUE #1802: Multipath analysis view not showing
There has been some interest in the multi-path view.

I just tried it.  It doesn't show at all on Linux.  The graph doesn't show on MS Windows.

Investigate.

## Steps to reproduce
* Open Debrief
* Open **MultiPath** folder in **sample_data**
* Open file **GapsTestTrack.dpf**
* Open **Multipath analysis** View
* Drag **GapsTestIntervals.csv** file onto **Intervals** placeholder
* Drag the **Depth** slider until the two graphs lie over each other

### PR DESCRIPTION
**Pull request by theanuradha**
Fixes #1802 

image

### CODE REVIEW

**Comment by IanMayo** [comment]
Hey - good bug-hunting, @theanuradha

**Comment by IanMayo** [comment]
@theanuradha - afraid the fix still isn't working for me:
blankmultipath

I'm under Linux.  I'll test it in MS Windows VM.

**Comment by IanMayo** [comment]
Aah, the fix is working under MS Windows.

That makes this a Linux-specific issue. Damn.  Issue re-opened.

**Comment by theanuradha** [comment]
@IanMayo you do not even have other labels that is strange [SVP: etc.. \

**Pull request merged**
