### PR TITLE
#1688 Show Context/selection info in Properties view

### PR DESCRIPTION
**Pull request by theanuradha**
context_1

Multi-select 
context_multi_1

### CODE REVIEW

**Comment by IanMayo** [comment]
Anu, what if 50 items are selected? What if the track has a really long name? Could you look into these edge cases?

**Comment by IanMayo** [comment]
Oh, it's also possible to view the current highlighter (from the time controller), an XY plot (time-variable), or a file from the navigator.

**Comment by theanuradha** [comment]
@IanMayo  it it long list it will show possible and tooltip will show full list

**Comment by theanuradha** [comment]
@IanMayo time controller & file from the navigator. all use default version without context

**Comment by theanuradha** [comment]
@sambireddyt  Agree on resource & SWTResourceManager, But this case it only create when editor is open and dispose when editor is closed. so editor itself self cache the bold font on PlotPropertySheetPage and unload itself when editor no longer needed.

**Comment by IanMayo** [comment]
@theanuradha - would you mind double-checking the commit I made that limits how many labels are shown: https://github.com/debrief/debrief/pull/1737/commits/8af2c3b48b6403a8d4bd6ffc220395dbc45ed401

Does the logic look ok?

**Comment by theanuradha** [comment]
@IanMayo Yes it looks good! in case you need tooltip to show full list lest me know I can fix it

**Pull request merged**
