### PR TITLE
4964 Relative paths to image files

### LINKED ISSUE #4964: Path of GeoTiff in DPF files not portable
We can include GeoTiff images in our plots - analysts use this a lot.

Debrief stores the absolute path to the image in the `layerPath` attribute.  This is ok for multiple users when the images comes from a shared network folder, since the path probably matches.  But, it fails if the dpf plus GeoTiff are zipped up and sent to someone else.  

Another example of this is for the `sample_data` that we distribute with Debrief.  A new user can load a `.dpf` file which includes a GeoTiff file in the current folder, but Debrief will fail to load it.

How do we handle this?  

1. When saving an `externalDataFile` object, see if it's in the same folder as the `.dpf` file.  If it is, just use a relative reference
2. When loading an `externalDataFile` object, if the file-load fails, have another go, using a relative path reference.
3. If the above fails, get the absolute reference to the `.dpf` file and see if the image file is present in the same directory.  If it is, load it.

Hmm, but the issue may be that we don't know the default folder location that Debrief is using as `home directory`.

We should investigate this further, to see what the options are.

**Note**: a recent PR introduces a GeoTiff image file, and a `.dpf` file that refers to it.  The `.dpf` needs to be manually _fixed_ to work on each new PC it's stored on, because of the above issue:
https://github.com/debrief/debrief/pull/4963

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #4964 
the path was appending the incorrect absolute path  instead of just the file name

### CODE REVIEW

**Review by IanMayo — APPROVED** [review]
Solution works for me, but welcome wider testing from @helenayele

**Comment by ayeshare** [comment]
Here is the issue that  Helen reported(on slack). If the file already has a tif file that could not be loaded, then on dropping the tif file without deleting the layer, there is an error:
java.lang.NullPointerException
	at org.geotools.renderer.lite.CompositingGroup.splitOnCompositingBase(CompositingGroup.java:160)
	at org.geotools.renderer.lite.CompositingGroup.splitOnCompositingBase(CompositingGroup.java:64)
	at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:838)
	at org.mwc.cmap.geotools.gt2plot.GeoToolsPainter.drawAwtImage(GeoToolsPainter.java:91)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart.paintBackground(SWTChart.java:922)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart.paintMe(SWTChart.java:1010)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas.paintPlot(SWTCanvas.java:511)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas.repaintMe(SWTCanvas.java:603)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas$4.paintControl(SWTCanvas.java:346)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1654)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4816)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4778)
	at org.eclipse.swt.internal.win32.OS.RedrawWindow(Native Method)
	at org.eclipse.swt.widgets.Control.update(Control.java:4595)
	at org.eclipse.swt.widgets.Control.update(Control.java:4588)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1870)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:330)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by helenayele** [comment]
But now @ayeshare  when I drop a file on the dpf file, it now tries to add the tif file , but it doesn't add double slash on the path. And due to this the tiff file can't be loaded.
it loads like this
[Image from Gyazo](https://gyazo.com/c64d9dca19c150a70ddd5b7835af9d32)
Can we add double slash on windows OS so that the tiff file can be loaded?

**Review by helenayele — CHANGES_REQUESTED** [review]
It still couldn't load the tif files from the unzipped folder:
[Image from Gyazo](https://gyazo.com/5303db90d87e69c56ecf04a0e723b773)
and it looks like this:
[Image from Gyazo](https://gyazo.com/7eb072db272248dc2e06278bffd43def)

**Comment by ayeshare** [comment]
>>But now @ayeshare when I drop a file on the dpf file, it now tries to add the tif file , but it doesn't add double slash on the path. And due to this the tiff file can't be loaded.

Cant reproduce this. It reloads the file even without the double backslash.

>>Here is the issue that Helen reported(on slack). If the file already has a tif file that could not be loaded, then on dropping the tif file without deleting the layer, there is an error:

I cannot reproduce this too.

**Comment by IanMayo** [comment]
@ayeshare  - the issue _may_ be that @helenayele  is loading the plot-file from a child folder in her Navigator.

We need to support loading DPF files from both the Navigator and the file system, obvs :-D

**Review by helenayele — COMMENTED** [review]
On this fix, able to load the tif files from navigator like
[Image from Gyazo](https://gyazo.com/ebaeaa17efc7448dffeec1b1510e8e13)

But when I try to drag the dpf file from file system, the tif files are not loaded automatically like the above, they are only loaded when I drag them. See these videos:
[Image from Gyazo](https://gyazo.com/ee37bb32a99bf2e56737aab36f3a0f4e)
[Image from Gyazo](https://gyazo.com/67cc42297a7c781b980905da90a7d2dd)

**Comment by ayeshare** [comment]
>>But when I try to drag the dpf file from file system, the tif files are not loaded automatically like the above, they are only loaded when I drag them
@helenayele I am able to drag the dpf file from filesystem even though I gave an incorrect path for the tif file in the dpf file

**Review by helenayele — APPROVED** [review]
Now Tiff files can be loaded both from file system with space and without space paths and from eclipse workspace from navigator.
So Approving...

**Pull request merged**
