### PR TITLE
4439 non set time debrief lite

### LINKED ISSUE #4439: Change default Date for newly created labels
Currently the default value for start and end Date of newly created label is set as 31/12/69 and time is set as 23:59:59
[Image from Gyazo](https://gyazo.com/18e077b9bef9f645969b257b766468e2)

And user complains about this and Ian suggests like this
 "it would be more logical to use today’s date (or the mid-point of the currently loaded data)"

### Steps to reproduce:

1. Launch D-Lite
2. Insert Label
3. Open label property and see the Start and End date

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4439

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Good evening @helenayele .
I have added a minimum size for the Text Fields.
Regarding the number 2, I think it was done like that by design. I can change it if needed.

**Comment by IanMayo** [comment]
> Regarding the number 2, I think it was done like that by design. I can change it if needed.

Yes, that seems like valid behaviour.

**Comment by IanMayo** [comment]
Hello @saulhidalgoaular  & @helenayele - having "Unset" as a value does seem a tidier solution - it correctly indicates that there isn't a time assigned.

Hmm, I guess we could alternatively use `dd:mm:yy` and  `hh:mm:ss` as the "unset" markers, since these will guide/prompt the user in how to format the text.

How does that sound?

BTW - I don't see the "not set" markers in the current version of this branch, I just see the current date/time.

**Comment by helenayele** [comment]
I can see the not set for null  date time values : [Image from Gyazo](https://gyazo.com/6c1db6cee1636d31399b2f5ab3f4850d)

I would also suggest to put the date format value instead of 'Not Set' for null values.

**Comment by IanMayo** [comment]
Minor change to make box wider , so it shows full content of date/time.

**Pull request merged**
