### PR TITLE
Fixed pasting track to a layer

### LINKED ISSUE #4929: Trouble saving data
* I have just opened Debrief and loaded the sample rep file BULK_BLUE_TRACKS
* In outline box I have selected the drop down menu and selected 'Create New Layer'.
* I named the layer 'Layer made in Outline'
* I selected the track 'T23_A' and cut it
* Then pasted into the layer
* I have saved the file as 'layer loss test.dpf'
* Following this I have the error: 'Exception Caught: Debrief Exporter not found for <SHIP NAME>
* The layer is now empty of any data.

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #4929 

Added Handler for TrackWrapper to be able to add trackwrapper to a layer

### CODE REVIEW

**Comment by IanMayo** [comment]
@ayeshare - sorry, you've misinterpreted what is required: https://github.com/debrief/debrief/issues/4929#issuecomment-663082663

Your fix is quite valid, but for legacy reasons, Debrief _currently_ only works with Heavyweight tracks at the top level of the Outline View.  This is partly to speed up the task of providing the user with a list of currently loaded tracks. By only looking for them at the top level it avoids navigating down through the layer tree to find all tracks.

So, the fix we require at the moment is to prevent a HeavyWEight track from being pasted into a Layer (folder).

**Comment by helenayele** [comment]
As per this fix, we have allowed to copy Heavyweight tracks inside a folder in full debrief.

**Comment by IanMayo** [comment]
No, Helen, the fix is to block pasting a track into a layer.

**Comment by helenayele** [comment]
> No, Helen, the fix is to block pasting a track into a layer.

But now we are able to paste Track:23_A in to our new layer like this 
[Image from Gyazo](https://gyazo.com/fbe8ded8794bf187a86156e27fc70e3e)
Is it okay?

**Comment by ayeshare** [comment]
I will fix in a new PR

**Comment by IanMayo** [comment]
I'm closing this PR, since we right now we don't want to allow pasting a heavyweight track into a layer.

**Pull request closed without merging**
