### PR TITLE
4869 date filter validation

### LINKED ISSUE #4869: Validate start date is before end date in Time period
Currently we don't validate that start date is before or on the same date of end date in import db dialog. 
Here is the screenshot:
[Image from Gyazo](https://gyazo.com/b2f61b4041326500a7ca89580e9dc246)

So when user inputs start date we need to validate that start date is always before or on the same date of end date.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4869

### CODE REVIEW

**Comment by IanMayo** [comment]
@saulhidalgoaular  - I see the start date box isn't wide enough to show the full date.

**Comment by helenayele** [comment]
did we merge the PR that fix the width of the start /end time input?

**Comment by IanMayo** [comment]
> did we merge the PR that fix the width of the start /end time input? that is #4868 , it is not still merged @IanMayo

#4868 now merged :-)

**Comment by IanMayo** [comment]
@helenayele - now that the text box size PR is merged, could you re-check please?

**Comment by helenayele** [comment]
yes the width of the start/end date time fields are  now increased and looks like 
[Image from Gyazo](https://gyazo.com/c6f5c12e01b9e80a21f65c77d5ae53f4)

**Pull request merged**
