### PR TITLE
4255 single track as default

### LINKED ISSUE #4255: Select a track by default when  single track found in the plot
When user opens  a rep/dpf file with single track, we show Speed, Course and Depth graphs in select graph combo. And after user selects his/her graph , it is better to select the single track found in the plot by default instead of waiting for user selection to show the graph. Because it is pointless to wait for user to select the lonely track found in the plot. 
[Image from Gyazo](https://gyazo.com/450187a0574e67fa229bf325c9f86c4e)
### Expected Behavior
Select the single track found in the plot - don't wait for user track selection in select track combo to show the graph

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4255

### CODE REVIEW

**Comment by IanMayo** [comment]
@helenayele - did you get chance to check this graph fix works ok?

**Comment by IanMayo** [comment]
Aah yes, @helenayele - I see what you mean.

@saulhidalgoaular - would it be possible to leave that first track selected, when new data is loaded.

**Comment by IanMayo** [comment]
@helenayele - does it work on when the track is deleted?

**Comment by helenayele** [comment]
Yes , when I delete the secondly added track, the graph for the first Track is shown:
https://screencast-o-matic.com/watch/cqji2MOMeC

**Comment by IanMayo** [comment]
Keeping it open, in the hope @saulhidalgoaular  can make the single track remain selected when the second one is loaded.

**Comment by saulhidalgoaular** [comment]
> Keeping it open, in the hope @saulhidalgoaular can make the single track remain selected when the second one is loaded.

Sure. I will do it now

**Comment by helenayele** [comment]
@saulhidalgoaular thanks please do

**Comment by saulhidalgoaular** [comment]
> The graph stays there when I add other track on the map panel.
> 
> But I see this debugging console messages :
> Plot was created on Mon Apr 08 14:52:36 EAT 2019
> El modelo tiene el track COLLINGWOOD false
> El modelo tiene el track COLLINGWOOD true
> El modelo tiene el track NELSON false
> Cambiando el primario COLLINGWOOD
> Primario cambio PRIMARY_CHANGED

Hi Helen. It is not 100% ready. I see sometimes it crashes. I am still debugging it a bit more to find what is happening.

**Comment by saulhidalgoaular** [comment]
Hi. Sometimes it crashes when you add and remove tracks. It is very hard to reproduce it. I conclude It is not related with the patch I am adding here.

Bug I mention is related with the TrackWrapper Segments (_theSegments variable). It says it has elements and then it says it doesn't have.
Lines of Interest:
TrackWrapper.java@2276  <--- Here is says it is not empty.
TrackWrapper.java@2693  <--- Here it is empty.

This bug should also be in Full Debrief. I am creating a ticket for it.

**Comment by helenayele** [comment]
Tried my best to break it, but not that much lucky, will keep my eye on it.

**Comment by IanMayo** [comment]
@helenayele - I've made a change to overcome the compiler warning. 

Would you mind double-checking that I haven't broken it?

**Comment by IanMayo** [comment]
Ok, @helenayele - we're tracking the add/remove undo/redo issues separately, so I'll close this one.

**Pull request merged**
