### PR TITLE
3878 geotools upgrade [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Supports #3878

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @saulhidalgoaular,
did we get any compile problems because of API changes?

**Comment by IanMayo** [comment]
Aah yes, I see we did. I guess of those are due to Units of Measurement.

Hopefully there's a straightforward fix.

**Comment by saulhidalgoaular** [comment]
> Aah yes, I see we did. I guess of those are due to Units of Measurement.
> 
> Hopefully there's a straightforward fix.

Yes. I am working on it now!

**Comment by IanMayo** [comment]
We've going to drop this PR, since to do the change we need to upgrade to Java 8.

Ian has to manage the customer expectations on Java 8+ before we can do that.

**Pull request closed without merging**
