### PR TITLE
4199 Pause step control when a track is deleted.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Supports #4199 
It looks like it is finished, but I would like to implement it with listeners as mentioned. I will retake it when I finish the drag feature.

### CODE REVIEW

**Comment by IanMayo** [comment]
Yes, @saulhidalgoaular - you're welcome to implement a more robust method too/instead, if you wish.

**Comment by helenayele** [comment]
And also after inserting label, all time control items are enabled and looks like this :
[Image from Gyazo](https://gyazo.com/5ca7e8d8aa694152d032f94271d4dcfe)
We need to enable them if we have only track in our plot.

**Comment by helenayele** [comment]
@saulhidalgoaular After I delete the track from outline view, The Filter to Time is not disabled, and after changing the start /end time, all the time player components are enabled. And after that when I click Play , the track seems playing in the background.
[Image from Gyazo](https://gyazo.com/dc270d25d74f0fffe9b1b673d7dc3387)

**Comment by helenayele** [comment]
Currently all the time menus including the Filter to Time component is getting disabled while we have no opened tracks in our plot. But I see 2 issues following these steps after deletion:

### Steps:
1. Open boat1.rep
2. On the graph pane, select Course graph and select the Nelson track to see the graph
3. Play the track from Time control
4. While playing, delete Nelson Track from outline view
5. See that every toolbar button from Time menu is disabled and graph is resetted as well
6. Drag boat2.rep file and play it
7. Drag boat1.rep file and select Play
See that Nelson track's marker is not shown, and the track is not playing
[Image from Gyazo](https://gyazo.com/e587d12af85a611e89435c7bc29e2aff)
8. Delete CoolingWood track from outline 
9 . Select Play , see that the CoolingWood track's marker/highlighter is still moving. 
[Image from Gyazo](https://gyazo.com/99db3c0e4f701ee43f5c600686547982)

**Comment by saulhidalgoaular** [comment]
> Currently all the time menus including the Filter to Time component is getting disabled while we have no opened tracks in our plot. But I see 2 issues following these steps after deletion:
> 
> ### Steps:
> 1. Open boat1.rep
> 2. On the graph pane, select Course graph and select the Nelson track to see the graph
> 3. Play the track from Time control
> 4. While playing, delete Nelson Track from outline view
> 5. See that every toolbar button from Time menu is disabled and graph is resetted as well
> 6. Drag boat2.rep file and play it
> 7. Drag boat1.rep file and select Play
>    See that Nelson track's marker is not shown, and the track is not playing
>    [Image from Gyazo](https://gyazo.com/e587d12af85a611e89435c7bc29e2aff)
> 8. Delete CoolingWood track from outline
>    9 . Select Play , see that the CoolingWood track's marker/highlighter is still moving.
>    [Image from Gyazo](https://gyazo.com/99db3c0e4f701ee43f5c600686547982)

I think this behavior is expected, because we haven't merged this branch with the patch that fixes the "ghost ships". I will merge it with Develop to confirm it.

**Comment by helenayele** [comment]
Yes Right! the above issues are no more reproducible.

**Pull request merged**
