### PR TITLE
5037 [Pepys] Extra information about database connection.

### LINKED ISSUE #5037: Include Pepys database URL in "Test connection" dialog
It would be useful to have confirmation of which database Debrief is connected to.

The contents of `db_name` would be enough to double-check where Debrief is connecting to.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #5037

### CODE REVIEW

**Comment by IanMayo** [comment]
Can we have a screenshot please @saulhidalgoaular ?

**Comment by saulhidalgoaular** [comment]
> Can we have a screenshot please @saulhidalgoaular ?

Good morning. Sure.

image

image

**Comment by IanMayo** [comment]
aah, I've just remembered something else. The dialog needs a Debrief icon,
on windows it currently uses a default windows one.

**Review by helenayele — CHANGES_REQUESTED** [review]
it looks like
[Image from Gyazo](https://gyazo.com/7d7c6841951e42a75d6ec289aecba8cb)
It needs window title and icon

**Comment by saulhidalgoaular** [comment]
Good morning.
I am not sure if it is possible to assign an icon to the Messagebox. At least not trivially.
I have added an icon and title for the Pepys Dialog Box.

**Comment by saulhidalgoaular** [comment]
image

**Comment by helenayele** [comment]
Okay @saulhidalgoaular  , it looks like this at my end
[Image from Gyazo](https://gyazo.com/31001cbefe6474bf21b9ab7559dcc94f)
and the decision is @IanMayo 's

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
