### PR TITLE
Stacked charts improvements

### PR DESCRIPTION
**Pull request by IanMayo**
Collection of fixes related to Tactical Overview

### CODE REVIEW

**Comment by IanMayo** [comment]
Build failing, since it depends on Limpet update.  Will re-run build when Limpet 333 is merged:
https://github.com/debrief/limpet/pull/333

**Comment by IanMayo** [comment]
@theanuradha - I could do with a hand here, please.  This build is failing because the StackedCharts.model code it's linking to is missing this function:
````
  courseStyle.setIncludeInLegend(false);
````

That's a feature that was merged in as part of Limpet PR: https://github.com/debrief/limpet/pull/333

I'm afraid I don't quite understand how we pull Limpet code into the Travis build for Debrief.

Could you:
a)  teach me how/where this build gets the Limpet code?
b)  resolve the problem, so this PR builds correctly?

**Comment by theanuradha** [comment]
@IanMayo Debrief connect Limpet via limpet update site. so current latest in Limpet update site will be ref to  Debrief.

IM looking in to why it has this issue

**Comment by theanuradha** [comment]
issue seems happen due to when this build ran update site was not updated .

**Comment by theanuradha** [comment]
I Just ran builds again and they seems fine now. maybe when next time limpet update wait till limpet build is complete to avoid this

**Pull request merged**
