### PR TITLE
3924 graph toolbar

### LINKED ISSUE #3924: M1.6.2.9.3 Implement graph toolbar
Full Debrief has quite a complex graph toolbar (and drop-down):
image

Consider which features we want in D-Lite, and create a UI toolbar in the new panel, to implement them.

The code for the features is probably mostly in `XYPlotView`.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #3924 #3928 #3923 #3927

### CODE REVIEW

**Comment by saulhidalgoaular** [comment]
Those unused variables will be fixed once we integrate it with the XP plot component.

**Comment by IanMayo** [comment]
> Those unused variables will be fixed once we integrate it with the XP plot component.

sure, ok :-)

**Comment by IanMayo** [comment]
@saulhidalgoaular - please tell us when it's ready for review.

**Comment by IanMayo** [comment]
Looking good @saulhidalgoaular 

But, could you left-align the toolbar?

**Comment by saulhidalgoaular** [comment]
> Looking good @saulhidalgoaular
> 
> But, could you left-align the toolbar?

Good morning. Sure!

**Comment by IanMayo** [comment]
@saulhidalgoaular  - I've done some meddling.  This branch makes changes to ShowTimeVariablePlot3, and XYPlotUtilities.  I've made those changes in `master`, then pulled them back into here.  That will prevent `master` and `develop` diverging too far.

**Comment by IanMayo** [comment]
@saulhidalgoaular - there are still come CodeFactor issues, but I'm happy to ignore those.

**Comment by saulhidalgoaular** [comment]
> @saulhidalgoaular - I've done some meddling. This branch makes changes to ShowTimeVariablePlot3, and XYPlotUtilities. I've made those changes in `master`, then pulled them back into here. That will prevent `master` and `develop` diverging too far.

Perfect. Thanks.

**Comment by IanMayo** [comment]
@saulhidalgoaular - I'm struggling to resolve the conflict with OutlinePanelView.  I'll carry on tomorrow.

I _don't think_ you've made any serious changes to it - just the fix for `editable.getInfo()` instead of just `editable`, at around line 384

**Comment by IanMayo** [comment]
@saulhidalgoaular  - is this ready for merge?  (Acknowledging that it contains some known issues, and some unknown issues)

**Pull request merged**
