### PR TITLE
#1439 undo redo toolbar with new icons and correct location

### PR DESCRIPTION
**Pull request by theanuradha**

### CODE REVIEW

**Comment by IanMayo** [comment]
Nicely done.  I did briefly wonder whether it was better to add the functionality to Debrief.core or cmap.core.  But, I see that there isn't any menu creation in cmap.core - it's all in Debrief.core, so you've done the right thing :-)

**Comment by IanMayo** [comment]
Hmm, @theanuradha - on Linux I don't get icons on Menus.  I think you're on OSX.  Do you get **Undo/Redo** icons on the **Edit** menu?  If so, do they show the old Eclipse icon?  We need them to use the new icons.

**Comment by theanuradha** [comment]
@IanMayo  I will fix menu icons

**Comment by theanuradha** [comment]
@IanMayo as side note: while we have custom icon for Save on toolbar menu icon is eclipse default

**Comment by IanMayo** [comment]
@theanuradha - nicely spotted.  I'm flashing up a Win7 VM, and will have a look.

Could you include a fix for that Save icon?

**Comment by theanuradha** [comment]
@IanMayo  sure will fix Save as well , issue on Save is it need 3 icons Save,Save As and Save all

**Comment by IanMayo** [comment]
@theanuradha - aah, yes.   Let's just fix undo/redo.  Could you create a new issue for the other icons?  I'll get the designer on it.

**Pull request merged**
