### PR TITLE
#1686 Multi line text editor

### PR DESCRIPTION
**Pull request by theanuradha**
multi-line-editor

### CODE REVIEW

**Comment by IanMayo** [comment]
@theanuradha - are you able to produce an editor that appears in the same space as the property?  Like in Sambi's mockup:
https://github.com/debrief/debrief/issues/1686#issuecomment-212711199

**Comment by theanuradha** [comment]
right now no. But I can make it

**Comment by theanuradha** [comment]
multi-line-editor_inplace

**Comment by theanuradha** [comment]
@IanMayo  changes on in-place mode is in.

**Comment by theanuradha** [comment]
@IanMayo  by mistake seems I have push change that not belong to this branch, I have revert that change. SO it should be fine , if not let me know will recreate with new branch only have correct changes.

**Comment by IanMayo** [comment]
Hi there, we have an untidy situation where the text looks different in view & edit modes.

In view mode, the text is multi-line, as it would appear on the plot:
viewmode

But, in edit mode, line-break chars are inserted:
editmode

Actually I think it would be acceptable to not allow inline editing - to just have the view mode, or click on the [...] button to open the popup editor (similar to how we handle color & font).

Could you make that change?

**Comment by IanMayo** [comment]
Oh, and please note @theanuradha - I've added a commit that makes the editor slightly smaller.

**Comment by theanuradha** [comment]
@IanMayo  Im on it

**Comment by IanMayo** [comment]
Hi there Anu - I've also just pushed a commit that introduces scrollbars.  You'll need to merge your changes with that.

Oh, one last thing: Sambi's original suggestion included the ability for the dialog to resize - could you include this:

resizable dialog

**Comment by theanuradha** [comment]
@IanMayo I added simplified mode. will be complicated to add resize support but I can try.

**Comment by IanMayo** [comment]
Thanks for the simplification - that's great.

>  I added simplified mode. will be complicated to add resize support but I can try.

Ok, let's not add complexity. Let's only do it if we can support resize via SWT.RESIZE flags, or less than 10 extra lines of code.

**Comment by theanuradha** [comment]
@IanMayo SWT.RESIZE only works with Dialog TRIM, custom code will be complex for sure.

**Comment by IanMayo** [comment]
Aah, @theanuradha - there's one remaining UI glitch.

I don't know if this is Linux specific or not, but...  As we switch from view to edit mode, the text moves a few pixels up and to the left.  Can you prevent this?  I guess the edit-mode label needs a few pixels offset.

**Comment by IanMayo** [comment]
> @IanMayo SWT.RESIZE only works with Dialog TRIM, custom code will be complex for sure.

Ok, let's not support resize.

**Comment by theanuradha** [comment]
@IanMayo  can you send screenshot off offset issue ? 
on mac
multi-line-editor_update

**Comment by IanMayo** [comment]
Ok, the "jump" is before the dialog has opened. So, when the "Label" property is selected, the text moves slightly up and to the left.

I've tried to shade in the pixels that are lost in this composite image that includes snippets of the property once selected:

viewmode2

**Comment by theanuradha** [comment]
@IanMayo looks like OS specific, can you see same issue happen on font editor ?

**Comment by IanMayo** [comment]
Yes, I get the slight shift for font editor on Linux.

Ok, it's probably OS-specific let's ignore it.

**Comment by IanMayo** [comment]
Fixes #1686

**Pull request merged**
