### PR TITLE
fixed a bug in saveas

### LINKED ISSUE #3789: Null Pointer Exception while Selecting No/Cancel options of 'Select an Option' dialog
When I try to save a file with the same name, it brings this dialog -
 [Image from Gyazo](https://gyazo.com/beced2060176937b1e93f0500c2fc515)

And when I select No or cancel, it logs NPE with this stack trace 
[NullPointerException_overwrite_No.txt](https://github.com/debrief/debrief/files/2889585/NullPointerException_overwrite_No.txt)

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #3789

### CODE REVIEW

**Comment by helenayele** [comment]
The exception is still reproducible while clicking No and Cancel buttons

**Comment by IanMayo** [comment]
Note: I don't get NPE when clicking `No` or `Cancel` buttons.

**Comment by helenayele** [comment]
Still Reproducible

Steps:
1. Have boat1.dpf in your sample_data folder
2. Open boat1.rep file 
3. Select New > Save,  try to save with the same default name given. Then it asks you to replace it or not
4. Select No or cancel

This time  , NPE is logged.

The exception happens in the last save dialog - 
image

**Comment by IanMayo** [comment]
@helenayele - fix for NPE on `new` added.

**Comment by helenayele** [comment]
Thanks works perfect!

**Pull request merged**
