### PR TITLE
4986 GeoPDF dialog title renaming

### LINKED ISSUE #4986: Geo-PDF Warn users about performance issue when the track has more than 100 steps.

### PR DESCRIPTION
**Pull request by saulhidalgoaular**
Fix #4986

### CODE REVIEW

**Comment by IanMayo** [comment]
Hey @saulhidalgoaular  - any chance of a screenshot?

**Comment by saulhidalgoaular** [comment]
Good afternoon @IanMayo . Sure
image

**Comment by IanMayo** [comment]
Thanks @saulhidalgoaular 

Could you change the title to just `GeoPDF Export` please?  The dialog contents pass on the message. The role of the title is just to give context, IMHO.

**Comment by saulhidalgoaular** [comment]
Good afternoon.

Changed as specified. 

image

**Review by helenayele — APPROVED** [review]
Thanks @saulhidalgoaular , Now looks like 
[Image from Gyazo](https://gyazo.com/24ed9c4e0223779e4377ed906f0c1937)

so approving...

**Pull request merged**
