### PR TITLE
fixed bug and cleaneup unnecessary code

### LINKED ISSUE #4959: Issues on Show source and show type options while changing the visibility of narrative entries
When we change the visibility of the narrative entries from outline view, all the columns of the narrative entries in narrative viewer will be shown. But show source and show type options doesn't get updated or will not have the correct status.

### Steps to reproduce:
1. Open sample.dpf
2. Open narrative viewer
3. See that narrative viewer  is shown with all columns 
4. Uncheck `Show source` and `Show type` so that Source and Type columns will be hidden and it looks like [Image from Gyazo](https://gyazo.com/2edd77af67e0c8c48def17d6e0431368)
5. Go to in outline view and uncheck one of the narrative entries there
6. It shows both `source` and `Type` columns but if you check `show source` and `show type` they remain unchecked
[Image from Gyazo](https://gyazo.com/78cd9a19e502de5633126faabbcb6286)
7. And if you try to export to word doc , it doesn't show the source and type columns.
[Image from Gyazo](https://gyazo.com/bd95c8a92edf338dcc8606c0b3c1a5fc). This is because `show source` and `show type` options are unchecked.

### PR DESCRIPTION
**Pull request by ayeshare**
Fixes #4959

### CODE REVIEW

**Comment by ayeshare** [comment]
@IanMayo @helenayele this is fixed now

**Review by helenayele — CHANGES_REQUESTED** [review]
Still reproducible...

[Image from Gyazo](https://gyazo.com/3d33255be4e9c3afe2011c25d3d351bc)

[Image from Gyazo](https://gyazo.com/3137c0a1869f213dea36dde470457ef0)

**Comment by helenayele** [comment]
On this fix, when changing the visibility of narrative entries from the outline view , it looks like this on narrative viewer:
[Image from Gyazo](https://gyazo.com/819892f03ff1958acf676db28b3fd045)
can we avoid this vibration ?
And the other issue is once I uncheck the show type and show source columns, they can't be shown even if I try to select them.
[Image from Gyazo](https://gyazo.com/c04104395bfdbcdea7427345b70cff3f)

**Review by helenayele — CHANGES_REQUESTED** [review]
1. Now changing the visibility of narrative entries from outline view doesn't change the visibility of columns in narrative viewer.
[Image from Gyazo](https://gyazo.com/556513c9fca218512cb919ed38af213f)
2.  And while changing the visibility it doesn't vibrate that much -acceptable
But the issue is after changing the visiblity of columns in narrative viewer, if I open new file, it doesn't respect my columns configuration  which was made by the previous opened file.
### Steps:
1. Open sample.dpf file
2. Open narrative viewer and uncheck the show Source and Show type options
3. Close the file and open narrative.rep file
See that it shows all columns but see that Show source and Show type options are unchecked.
[Image from Gyazo](https://gyazo.com/99a4c26e1047f7aa18bee6afb4e1768a)

**Comment by ayeshare** [comment]
@helenayele my fix was to remember the state of the narrative viewer.  So that, if a new file is opened or visibility of a narrative changes, it should not reset show source and type.

**Comment by helenayele** [comment]
> @helenayele my fix was to remember the state of the narrative viewer. So that, if a new file is opened or visibility of a narrative changes, it should not reset show source and type.

Okay @ayeshare  but it doesn't remember the previous configured state , it just shows all the columns , but Show Source and Show type options states are kept.

**Comment by ayeshare** [comment]
> > @helenayele my fix was to remember the state of the narrative viewer. So that, if a new file is opened or visibility of a narrative changes, it should not reset show source and type.
> 
> Okay @ayeshare but it doesn't remember the previous configured state , it just shows all the columns , but Show Source and Show type options states are kept.

Also the narratives are still displayed even after closing all the plots

**Comment by helenayele** [comment]
> Also the narratives are still displayed even after closing all the plots
But this issue doesn't happen in develop branch.

**Comment by helenayele** [comment]
> ### Steps:
> 1. Open sample.dpf file
> 2. Open narrative viewer and uncheck the show Source and Show type options
> 3. Close the file and open narrative.rep file
>    See that it shows all columns but see that Show source and Show type options are unchecked.

This issue now is not reproducible. 
But there seems serious error in updating narrative entries in narrative viewer when we change the visibility of narrative entries in outline view. When I make  a narrative entry invisible from outline view, it just selects the narrative entry in narrative viewer instead of removing it. But if I export that, the narrative entries which are marked invisible will not be shown in exported doc.
See this video
[Image from Gyazo](https://gyazo.com/219bd99185215de4e56c28ce813ab223)
And also  narrative viewer doesn't update its content when we change files.
See the below screenshot
[Image from Gyazo](https://gyazo.com/6ee5b8a946ecbe3e4e2de959961dc67a)
### Steps
1. Open sample.dpf file 
2. And it shows me its narrative entries, 
3. Open sen_tracks_with_narrative.dpf file
4. See that it shows still the narrative entries of sample.dpf file.

**Comment by ayeshare** [comment]
All issues are fixed on Natviewer.  The changes I made are if a new plot is opened, the nat viewer is reset and showsource and type are selected.  Otherwise the natviewer selections of showsource and showtype are selected.

**Review by helenayele — APPROVED** [review]
All the mentioned issue are fixed. 
And the remaining issue is tracked at #4970 ,
So approving...

**Pull request merged**
